<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<!-- Identity template to copy everything by default -->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='fighter_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='vlandia_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='vlandia_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='vlandia_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='vla_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='vla_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='vla_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='vla_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='vla_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='vla_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='vla_civ_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='vla_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='vla_noncom_template_flamboyant']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_battania']"/>
	<xsl:template match="NPCCharacter[@id='fighter_battania']"/>
	<xsl:template match="NPCCharacter[@id='battania_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='battania_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='battania_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='bat_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='bat_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='bat_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='bat_bat_template_wild']"/>
	<xsl:template match="NPCCharacter[@id='bat_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='bat_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='bat_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='bat_civ_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='bat_civ_template_wild']"/>
	<xsl:template match="NPCCharacter[@id='bat_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='bat_noncom_template_wild']"/>
	<xsl:template match="NPCCharacter[@id='bat_noncom_template_flamboyant']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='fighter_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='khu_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='khu_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='khu_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='khu_bat_template_nomad']"/>
	<xsl:template match="NPCCharacter[@id='khu_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='khu_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='khu_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='khu_civ_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='khu_civ_template_nomad']"/>
	<xsl:template match="NPCCharacter[@id='khu_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='khu_noncom_template_flamboyant']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_0']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_1']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_2']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_3']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_4']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_5']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_6']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_7']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_8']"/>
	<xsl:template match="NPCCharacter[@id='facgen_template_test_char_9']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_empire']"/>
	<xsl:template match="NPCCharacter[@id='guard']"/>
	<xsl:template match="NPCCharacter[@id='villager_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_empire']"/>
	<xsl:template match="NPCCharacter[@id='fighter_empire']"/>
	<xsl:template match="NPCCharacter[@id='civillian_template_gangster_tier1_empire']"/>
	<xsl:template match="NPCCharacter[@id='civillian_template_gangster_tier2_empire']"/>
	<xsl:template match="NPCCharacter[@id='civillian_template_gangster_tier3_empire']"/>
	<xsl:template match="NPCCharacter[@id='empire_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='empire_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='empire_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_stoic']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_southfrontier']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_northfrontier']"/>
	<xsl:template match="NPCCharacter[@id='emp_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_stoic']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_southfrontier']"/>
	<xsl:template match="NPCCharacter[@id='emp_civ_template_northfrontier']"/>
	<xsl:template match="NPCCharacter[@id='emp_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='emp_noncom_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='emp_noncom_template_stoic']"/>
	<xsl:template match="NPCCharacter[@id='emp_noncom_template_southfrontier']"/>
	<xsl:template match="NPCCharacter[@id='emp_noncom_template_northfrontier']"/>
	
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='fighter_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='sturgia_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='sturgia_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='sturgia_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='stu_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='stu_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='stu_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='stu_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='stu_bat_template_woodsman']"/>
	<xsl:template match="NPCCharacter[@id='stu_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='stu_civ_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='stu_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='stu_civ_template_woodsman']"/>
	
	<xsl:template match="NPCCharacter[@id='stu_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='stu_noncom_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='stu_noncom_template_woods']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_template_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_armed_wanderer_equipment_template_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_aserai']"/>
	<xsl:template match="NPCCharacter[@id='fighter_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_companion_equipment_template_aserai']"/>
	<xsl:template match="NPCCharacter[@id='aserai_troop_civilian_template_t1']"/>
	<xsl:template match="NPCCharacter[@id='aserai_troop_civilian_template_t2']"/>
	<xsl:template match="NPCCharacter[@id='aserai_troop_civilian_template_t3']"/>
	<xsl:template match="NPCCharacter[@id='ase_bat_template_medium']"/>
	<xsl:template match="NPCCharacter[@id='ase_bat_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='ase_bat_template_heavy']"/>
	<xsl:template match="NPCCharacter[@id='ase_bat_template_bedouin']"/>
	<xsl:template match="NPCCharacter[@id='ase_bat_template_lady']"/>
	<xsl:template match="NPCCharacter[@id='ase_civ_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='ase_civ_template_default']"/>
	<xsl:template match="NPCCharacter[@id='ase_noncom_template_flamboyant']"/>
	<xsl:template match="NPCCharacter[@id='ase_noncom_template_default']"/>
	<xsl:template match="NPCCharacter[@id='ase_noncom_template_bedouin']"/>
	
</xsl:stylesheet>