<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- region native armor -->
	<xsl:template match="Item[@id='headscarf_d']"/>
	<xsl:template match="Item[@id='open_head_scarf']"/>
	<xsl:template match="Item[@id='woven_turban']"/>
	<xsl:template match="Item[@id='turban']"/>
	<xsl:template match="Item[@id='desert_cap']"/>
	<xsl:template match="Item[@id='wrapped_desert_cap']"/>
	<xsl:template match="Item[@id='aserai_villager_female_headdress']"/>
	<xsl:template match="Item[@id='tuareg']"/>
	<xsl:template match="Item[@id='head_scarf']"/>
	<xsl:template match="Item[@id='desert_headdress']"/>
	<xsl:template match="Item[@id='female_head_wrap']"/>
	<xsl:template match="Item[@id='aserai_female_civil_hscarf']"/>
	<xsl:template match="Item[@id='aserai_female_civil_hscarf_b']"/>
	<xsl:template match="Item[@id='aserai_civil_c_head']"/>
	<xsl:template match="Item[@id='aserai_civil_f_cape']"/>
	<xsl:template match="Item[@id='aserai_civil_d_hscarf']"/>
	<xsl:template match="Item[@id='aserai_civil_e_hscarf']"/>
	<xsl:template match="Item[@id='aserai_civil_hscarf_a']"/>
	<xsl:template match="Item[@id='aserai_civil_hscarf_b']"/>
	<xsl:template match="Item[@id='tied_head_wrapping']"/>
	<xsl:template match="Item[@id='tight_head_scarf']"/>
	<xsl:template match="Item[@id='closed_head_scarf']"/>
	<xsl:template match="Item[@id='open_desert_helmet']"/>
	<xsl:template match="Item[@id='closed_desert_helmet']"/>
	<xsl:template match="Item[@id='loose_wrapped_desert_helmet']"/>
	<xsl:template match="Item[@id='trailed_desert_helmet']"/>
	<xsl:template match="Item[@id='desert_helmet_with_mail']"/>
	<xsl:template match="Item[@id='desert_helmet']"/>
	<xsl:template match="Item[@id='pointed_skullcap_over_mail']"/>
	<xsl:template match="Item[@id='pointed_skullcap_over_laced_coif']"/>
	<xsl:template match="Item[@id='pointed_skullcap_over_cloth_headwrap']"/>
	<xsl:template match="Item[@id='aserai_crown']"/>
	<xsl:template match="Item[@id='pointed_skullcap_over_mail_coif']"/>
	<xsl:template match="Item[@id='merchants_hat']"/>
	<xsl:template match="Item[@id='womens_headwrap_b']"/>
	<xsl:template match="Item[@id='womens_headwrap_c']"/>
	<xsl:template match="Item[@id='fur_hat']"/>
	<xsl:template match="Item[@id='pilgrim_hood']"/>
	<xsl:template match="Item[@id='head_wrapped']"/>
	<xsl:template match="Item[@id='head_wrapping']"/>
	<xsl:template match="Item[@id='headscarf_c']"/>
	<xsl:template match="Item[@id='wrapped_headcloth']"/>
	<xsl:template match="Item[@id='head_piece']"/>
	<xsl:template match="Item[@id='headscarf']"/>
	<xsl:template match="Item[@id='battania_civil_hood']"/>
	<xsl:template match="Item[@id='cloth_headwrap']"/>
	<xsl:template match="Item[@id='fur_hood']"/>
	<xsl:template match="Item[@id='eastern_cap']"/>
	<xsl:template match="Item[@id='laced_cloth_coif']"/>
	<xsl:template match="Item[@id='leather_cap']"/>
	<xsl:template match="Item[@id='nomad_cap']"/>
	<xsl:template match="Item[@id='nordic_leather_cap']"/>
	<xsl:template match="Item[@id='peaked_fur_hood']"/>
	<xsl:template match="Item[@id='upturned_fur_cap']"/>
	<xsl:template match="Item[@id='battania_crown']"/>
	<xsl:template match="Item[@id='decorated_nomad_cap']"/>
	<xsl:template match="Item[@id='empire_crown_north']"/>
	<xsl:template match="Item[@id='empire_crown_v2']"/>
	<xsl:template match="Item[@id='empire_crown_west']"/>
	<xsl:template match="Item[@id='vlandia_crown']"/>
	<xsl:template match="Item[@id='padded_cap']"/>
	<xsl:template match="Item[@id='padded_coif']"/>
	<xsl:template match="Item[@id='arming_cap']"/>
	<xsl:template match="Item[@id='imperial_cloth_coif']"/>
	<xsl:template match="Item[@id='nordic_fur_cap']"/>
	<xsl:template match="Item[@id='thinhide_coif']"/>
	<xsl:template match="Item[@id='laced_coif']"/>
	<xsl:template match="Item[@id='northern_fur_cap']"/>
	<xsl:template match="Item[@id='nomad_padded_hood']"/>
	<xsl:template match="Item[@id='open_padded_coif']"/>
	<xsl:template match="Item[@id='roughhide_cap']"/>
	<xsl:template match="Item[@id='arming_coif']"/>
	<xsl:template match="Item[@id='imperial_padded_coif']"/>
	<xsl:template match="Item[@id='imperial_leather_coif']"/>
	<xsl:template match="Item[@id='leather_studdedhelm']"/>
	<xsl:template match="Item[@id='leather_studdedhelm_over_headcloth']"/>
	<xsl:template match="Item[@id='leather_studdedhelm_over_thinhide']"/>
	<xsl:template match="Item[@id='wolfhead']"/>
	<xsl:template match="Item[@id='leather_studdedhelm_over_roughscale']"/>
	<xsl:template match="Item[@id='padded_leather_cape']"/>
	<xsl:template match="Item[@id='vlandia_bandit_cape_a']"/>
	<xsl:template match="Item[@id='vlandia_bandit_cape_b']"/>
	<xsl:template match="Item[@id='open_mail_coif']"/>
	<xsl:template match="Item[@id='battania_fur_helmet']"/>
	<xsl:template match="Item[@id='bearhead']"/>
	<xsl:template match="Item[@id='imperial_open_mail_coif']"/>
	<xsl:template match="Item[@id='mail_coif']"/>
	<xsl:template match="Item[@id='imperial_mail_coif']"/>
	<xsl:template match="Item[@id='khuzait_crown']"/>
	<xsl:template match="Item[@id='plumed_fur_lined_helmet']"/>
	<xsl:template match="Item[@id='empire_crown']"/>
	<xsl:template match="Item[@id='leatherlame_roundkettle']"/>
	<xsl:template match="Item[@id='cervelliere_over_laced_coif']"/>
	<xsl:template match="Item[@id='sturgian_crown']"/>
	<xsl:template match="Item[@id='cervelliere_over_padded_cap']"/>
	<xsl:template match="Item[@id='cervelliere_over_arming_coif']"/>
	<xsl:template match="Item[@id='segmented_cervelliere_over_laced_coif']"/>
	<xsl:template match="Item[@id='ironlame_roundkettle_over_imperial_leather']"/>
	<xsl:template match="Item[@id='nomad_helmet']"/>
	<xsl:template match="Item[@id='nasal_cervelliere_over_padded_cap']"/>
	<xsl:template match="Item[@id='spiked_kettle_over_imperial_padding']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_b_brnz']"/>
	<xsl:template match="Item[@id='spangenhelm_with_padded_cloth']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_c_cpr']"/>
	<xsl:template match="Item[@id='roundkettle_over_imperial_cloth']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_a_brnz']"/>
	<xsl:template match="Item[@id='peaked_helmet_over_laced_coif']"/>
	<xsl:template match="Item[@id='roundkettle_over_laced_cloth']"/>
	<xsl:template match="Item[@id='steppe_helmet']"/>
	<xsl:template match="Item[@id='battania_battle_crown']"/>
	<xsl:template match="Item[@id='roundkettle_over_imperial_padding']"/>
	<xsl:template match="Item[@id='spangenhelm_with_leather']"/>
	<xsl:template match="Item[@id='peaked_helmet_over_padded_cloth']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_d_brnz']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_c_brnz']"/>
	<xsl:template match="Item[@id='ironlame_spiked_kettle_over_mail']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_b']"/>
	<xsl:template match="Item[@id='leatherlame_roundkettle_over_imperial_mail']"/>
	<xsl:template match="Item[@id='roundkettle_over_imperial_leather']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_padded_cap']"/>
	<xsl:template match="Item[@id='plumed_lamellar_helmet']"/>
	<xsl:template match="Item[@id='ironlame_roundkettle_over_imperial_mail']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_a']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_laced_coif']"/>
	<xsl:template match="Item[@id='guards_kettle_over_laced_coif']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_padded_cloth']"/>
	<xsl:template match="Item[@id='kettle_hat_over_padded_coif']"/>
	<xsl:template match="Item[@id='segmented_cervelliere_over_mail']"/>
	<xsl:template match="Item[@id='tall_helmet']"/>
	<xsl:template match="Item[@id='kettle_hat_over_padded_cloth']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_padded_coif']"/>
	<xsl:template match="Item[@id='segmented_cervelliere_over_mail_coif']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_arming_coif']"/>
	<xsl:template match="Item[@id='kettle_helmet_with_leather']"/>
	<xsl:template match="Item[@id='roughscale_helmet']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_c']"/>
	<xsl:template match="Item[@id='guards_kettle_over_padded_coif']"/>
	<xsl:template match="Item[@id='desert_mail_coif']"/>
	<xsl:template match="Item[@id='visored_helmet_over_laced_coif']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_b_closed']"/>
	<xsl:template match="Item[@id='kettle_helmet_with_mail']"/>
	<xsl:template match="Item[@id='peaked_helmet_over_mail']"/>
	<xsl:template match="Item[@id='roundkettle_over_imperial_mail']"/>
	<xsl:template match="Item[@id='segmented_skullcap_over_mail_coif']"/>
	<xsl:template match="Item[@id='emirs_helmet']"/>
	<xsl:template match="Item[@id='spiked_helmet']"/>
	<xsl:template match="Item[@id='peaked_helmet_over_mail_coif']"/>
	<xsl:template match="Item[@id='western_crowned_helmet']"/>
	<xsl:template match="Item[@id='kettle_hat_over_mail_coif']"/>
	<xsl:template match="Item[@id='kettle_helmet_over_mail']"/>
	<xsl:template match="Item[@id='guards_kettle_over_mail_coif']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_leather']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_b_leather']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_open']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_b_open']"/>
	<xsl:template match="Item[@id='spiked_kettle_over_imperial_mail']"/>
	<xsl:template match="Item[@id='cervelliere_over_cloth_headwrap']"/>
	<xsl:template match="Item[@id='segmented_skullcap_over_padded_cloth']"/>
	<xsl:template match="Item[@id='western_crowned_plated_helmet']"/>
	<xsl:template match="Item[@id='empire_lord_helmet']"/>
	<xsl:template match="Item[@id='nasal_helmet']"/>
	<xsl:template match="Item[@id='nasal_cervelliere_over_laced_coif']"/>
	<xsl:template match="Item[@id='ironlame_nasalhelm_over_imperial_cloth']"/>
	<xsl:template match="Item[@id='ironlame_nasalhelm_over_imperial_coif']"/>
	<xsl:template match="Item[@id='segmented_cervelliere_over_padded_cloth']"/>
	<xsl:template match="Item[@id='ironlame_nasalhelm_over_imperial_padding']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_padded_cloth']"/>
	<xsl:template match="Item[@id='leatherlame_roundkettle_over_imperial_leather']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_padded_coif']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_laced_coif']"/>
	<xsl:template match="Item[@id='plumed_nomad_helmet']"/>
	<xsl:template match="Item[@id='leatherlame_nasalhelm_over_imperial_leather']"/>
	<xsl:template match="Item[@id='nasal_cervelliere_over_padded_coif']"/>
	<xsl:template match="Item[@id='nasal_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ironlame_feathered_spangenhelm']"/>
	<xsl:template match="Item[@id='nasal_helmet_with_mail']"/>
	<xsl:template match="Item[@id='nasalhelm_over_leather']"/>
	<xsl:template match="Item[@id='pointed_skullcap_with_mail']"/>
	<xsl:template match="Item[@id='segmented_skullcap_over_laced_coif']"/>
	<xsl:template match="Item[@id='nasalhelm_over_mail']"/>
	<xsl:template match="Item[@id='segmented_skullcap_over_padded_coif']"/>
	<xsl:template match="Item[@id='leatherlame_feathered_spangenhelm_over_leather']"/>
	<xsl:template match="Item[@id='ironlame_feathered_spangenhelm_over_leather']"/>
	<xsl:template match="Item[@id='nasal_cervelliere_over_mail_coif']"/>
	<xsl:template match="Item[@id='sturgian_helmet_base']"/>
	<xsl:template match="Item[@id='sturgian_helmet_open']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_mail']"/>
	<xsl:template match="Item[@id='leatherlame_nasalhelm_over_imperial_mail']"/>
	<xsl:template match="Item[@id='feathered_spangenhelm_over_imperial_coif']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_mail_coif']"/>
	<xsl:template match="Item[@id='aserai_battle_crown']"/>
	<xsl:template match="Item[@id='ironlame_nasalhelm_over_imperial_mail']"/>
	<xsl:template match="Item[@id='khuzait_battle_crown']"/>
	<xsl:template match="Item[@id='battania_earmuff_helmet_d']"/>
	<xsl:template match="Item[@id='helmet_with_faceguard']"/>
	<xsl:template match="Item[@id='ridged_northernhelm']"/>
	<xsl:template match="Item[@id='ironlame_feathered_spangenhelm_over_mail']"/>
	<xsl:template match="Item[@id='southern_noble_helmet']"/>
	<xsl:template match="Item[@id='imperial_nasal_helm']"/>
	<xsl:template match="Item[@id='leatherlame_feathered_spangenhelm_over_mail']"/>
	<xsl:template match="Item[@id='southern_lord_helmet']"/>
	<xsl:template match="Item[@id='battanian_noble_helmet_with_feather']"/>
	<xsl:template match="Item[@id='empire_battle_crown_north']"/>
	<xsl:template match="Item[@id='empire_battle_crown_west']"/>
	<xsl:template match="Item[@id='sturgia_heavy_cavalary_helmet']"/>
	<xsl:template match="Item[@id='sturgian_battle_crown']"/>
	<xsl:template match="Item[@id='sturgian_helmet_b_open']"/>
	<xsl:template match="Item[@id='khuzait_noble_helmet_with_feathers']"/>
	<xsl:template match="Item[@id='empire_helmet_with_metal_strips']"/>
	<xsl:template match="Item[@id='empire_jewelled_helmet']"/>
	<xsl:template match="Item[@id='western_plated_helmet']"/>
	<xsl:template match="Item[@id='khuzait_noble_helmet_with_neckguard']"/>
	<xsl:template match="Item[@id='nasal_helmet_over_cloth_headwrap']"/>
	<xsl:template match="Item[@id='goggled_helmet_over_leather']"/>
	<xsl:template match="Item[@id='battanian_plated_noble_helmet']"/>
	<xsl:template match="Item[@id='battanian_crowned_helmet']"/>
	<xsl:template match="Item[@id='empire_guarded_lord_helmet']"/>
	<xsl:template match="Item[@id='closed_desert_helmet_with_mail']"/>
	<xsl:template match="Item[@id='northern_goggled_helmet']"/>
	<xsl:template match="Item[@id='plumed_helmet']"/>
	<xsl:template match="Item[@id='goggled_helmet_over_mail']"/>
	<xsl:template match="Item[@id='sturgian_lord_helmet_a']"/>
	<xsl:template match="Item[@id='lendman_helmet_over_mail']"/>
	<xsl:template match="Item[@id='khuzait_noble_helmet_with_fur']"/>
	<xsl:template match="Item[@id='nordic_helmet']"/>
	<xsl:template match="Item[@id='heavy_nasalhelm_over_laced_cloth']"/>
	<xsl:template match="Item[@id='heavy_nasalhelm_over_imperial_padding']"/>
	<xsl:template match="Item[@id='heavy_nasalhelm_over_imperial_leather']"/>
	<xsl:template match="Item[@id='northern_warlord_helmet']"/>
	<xsl:template match="Item[@id='sturgian_lord_helmet_b']"/>
	<xsl:template match="Item[@id='heavy_nasalhelm_over_imperial_mail']"/>
	<xsl:template match="Item[@id='eastern_vendel_helmet']"/>
	<xsl:template match="Item[@id='brass_aserai_helmet_closed']"/>
	<xsl:template match="Item[@id='closed_goggled_helmet']"/>
	<xsl:template match="Item[@id='goggled_helmet_over_full_mail']"/>
	<xsl:template match="Item[@id='aserai_lord_helmet_a']"/>
	<xsl:template match="Item[@id='sturgian_helmet_b_close']"/>
	<xsl:template match="Item[@id='sturgian_helmet_closed']"/>
	<xsl:template match="Item[@id='decorated_goggled_helmet']"/>
	<xsl:template match="Item[@id='imperial_goggled_helmet']"/>
	<xsl:template match="Item[@id='lendman_helmet_over_full_mail']"/>
	<xsl:template match="Item[@id='sturgian_lord_helmet_c']"/>
	<xsl:template match="Item[@id='vlandia_lord_helmet_b2']"/>
	<xsl:template match="Item[@id='visored_helmet_over_padded_cloth']"/>
	<xsl:template match="Item[@id='visored_helmet_over_padded_coif']"/>
	<xsl:template match="Item[@id='spiked_helmet_with_facemask']"/>
	<xsl:template match="Item[@id='visored_helmet_over_mail_coif']"/>
	<xsl:template match="Item[@id='vlandian_faceguard_helmet_b']"/>
	<xsl:template match="Item[@id='full_helm_over_laced_coif']"/>
	<xsl:template match="Item[@id='full_helm_over_cloth_headwrap']"/>
	<xsl:template match="Item[@id='full_helm_over_arming_coif']"/>
	<xsl:template match="Item[@id='full_helm_over_padded_cloth']"/>
	<xsl:template match="Item[@id='full_helm_over_padded_cap']"/>
	<xsl:template match="Item[@id='full_helm_over_mail_coif']"/>
	<xsl:template match="Item[@id='vlandian_faceguard_helmet_a']"/>
	<xsl:template match="Item[@id='a_battania_cloak_a']"/>
	<xsl:template match="Item[@id='battania_civil_cloak']"/>
	<xsl:template match="Item[@id='battania_cloak']"/>
	<xsl:template match="Item[@id='female_hood']"/>
	<xsl:template match="Item[@id='scarf']"/>
	<xsl:template match="Item[@id='southern_shawl']"/>
	<xsl:template match="Item[@id='wrapped_scarf']"/>
	<xsl:template match="Item[@id='battania_civil_cape']"/>
	<xsl:template match="Item[@id='green_hood']"/>
	<xsl:template match="Item[@id='a_brass_lamellar_shoulder_a']"/>
	<xsl:template match="Item[@id='female_scarf']"/>
	<xsl:template match="Item[@id='desert_fabric_shoulderpad']"/>
	<xsl:template match="Item[@id='hood']"/>
	<xsl:template match="Item[@id='a_brass_lamellar_shoulder_white_a']"/>
	<xsl:template match="Item[@id='a_aserai_scale_b_shoulder_d']"/>
	<xsl:template match="Item[@id='a_empire_plated_shoulder_a']"/>
	<xsl:template match="Item[@id='battanian_leather_shoulder_a']"/>
	<xsl:template match="Item[@id='empire_cape_a']"/>
	<xsl:template match="Item[@id='desert_leather_shoulderpad']"/>
	<xsl:template match="Item[@id='leopard_pelt']"/>
	<xsl:template match="Item[@id='reinforced_suede_shoulders']"/>
	<xsl:template match="Item[@id='battania_scarf_a']"/>
	<xsl:template match="Item[@id='a_khuzait_leather_shoulder_b_b']"/>
	<xsl:template match="Item[@id='battania_cloak_b']"/>
	<xsl:template match="Item[@id='battania_shoulder_strap']"/>
	<xsl:template match="Item[@id='bolted_leather_strips']"/>
	<xsl:template match="Item[@id='stitched_leather_shoulders']"/>
	<xsl:template match="Item[@id='a_aserai_scale_b_shoulder_b']"/>
	<xsl:template match="Item[@id='a_khuzait_leather_shoulder_b_a']"/>
	<xsl:template match="Item[@id='a_pauldron_cape_c']"/>
	<xsl:template match="Item[@id='aserai_horseman_shoulder']"/>
	<xsl:template match="Item[@id='battania_shoulder_furr']"/>
	<xsl:template match="Item[@id='battania_woodland_cloak']"/>
	<xsl:template match="Item[@id='battania_shoulder_strap_cloak']"/>
	<xsl:template match="Item[@id='woven_leather_shoulders']"/>
	<xsl:template match="Item[@id='aserai_scale_shoulder_d']"/>
	<xsl:template match="Item[@id='empire_plate_armor_shoulder_a']"/>
	<xsl:template match="Item[@id='a_leather_lamellar_armor_shoulder_a']"/>
	<xsl:template match="Item[@id='varangian_bra_basic']"/>
	<xsl:template match="Item[@id='a_brass_lamellar_shoulder_b']"/>
	<xsl:template match="Item[@id='a_pauldron_cape_b']"/>
	<xsl:template match="Item[@id='chainmail_shoulder_armor']"/>
	<xsl:template match="Item[@id='empire_plate_armor_shoulder_b']"/>
	<xsl:template match="Item[@id='steppe_leather_shoulders']"/>
	<xsl:template match="Item[@id='a_empire_plated_shoulder_b']"/>
	<xsl:template match="Item[@id='battania_cloak_furr']"/>
	<xsl:template match="Item[@id='khuzait_leather_pauldron']"/>
	<xsl:template match="Item[@id='padded_leather_shoulders']"/>
	<xsl:template match="Item[@id='wolf_shoulder']"/>
	<xsl:template match="Item[@id='varangian_bra_royal']"/>
	<xsl:template match="Item[@id='a_aserai_scale_b_shoulder_c']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_shoulder']"/>
	<xsl:template match="Item[@id='leather_lamellar_shoulders']"/>
	<xsl:template match="Item[@id='a_brass_lamellar_shoulder_white_b']"/>
	<xsl:template match="Item[@id='a_metal_lamellar_armor_shoulder_a']"/>
	<xsl:template match="Item[@id='brass_scale_shoulders']"/>
	<xsl:template match="Item[@id='scale_shoulder_armor']"/>
	<xsl:template match="Item[@id='bearskin']"/>
	<xsl:template match="Item[@id='rough_bearskin']"/>
	<xsl:template match="Item[@id='battanian_chainmail_shoulder_a']"/>
	<xsl:template match="Item[@id='eastern_studded_shoulders']"/>
	<xsl:template match="Item[@id='varangian_bra_padded']"/>
	<xsl:template match="Item[@id='aserai_scale_shoulder_c']"/>
	<xsl:template match="Item[@id='a_aserai_scale_b_shoulder_a']"/>
	<xsl:template match="Item[@id='mail_shoulders']"/>
	<xsl:template match="Item[@id='pauldron_cape_a']"/>
	<xsl:template match="Item[@id='studded_imperial_neckguard']"/>
	<xsl:template match="Item[@id='battanian_chainmail_shoulder_b']"/>
	<xsl:template match="Item[@id='brass_lamellar_shoulder']"/>
	<xsl:template match="Item[@id='pauldron_with_cape']"/>
	<xsl:template match="Item[@id='imperial_studded_strip_shoulders']"/>
	<xsl:template match="Item[@id='varangian_bra_mail']"/>
	<xsl:template match="Item[@id='a_aserai_scale_b_shoulder_e']"/>
	<xsl:template match="Item[@id='aserai_scale_shoulder_a']"/>
	<xsl:template match="Item[@id='aserai_scale_shoulder_e']"/>
	<xsl:template match="Item[@id='brass_lamellar_shoulder_white']"/>
	<xsl:template match="Item[@id='lamellar_shoulders']"/>
	<xsl:template match="Item[@id='varangian_bra_scale']"/>
	<xsl:template match="Item[@id='aserai_scale_shoulder_b']"/>
	<xsl:template match="Item[@id='battania_warlord_pauldrons']"/>
	<xsl:template match="Item[@id='desert_scale_shoulders']"/>
	<xsl:template match="Item[@id='pauldron_over_scale_armor']"/>
	<xsl:template match="Item[@id='imperial_lamellar_shoulders']"/>
	<xsl:template match="Item[@id='noble_pauldron']"/>
	<xsl:template match="Item[@id='noble_pauldron_with_cape']"/>
	<xsl:template match="Item[@id='noble_pauldron_with_scarf']"/>
	<xsl:template match="Item[@id='armored_bearskin']"/>
	<xsl:template match="Item[@id='fur_cloak_a']"/>
	<xsl:template match="Item[@id='fur_cloak_b']"/>
	<xsl:template match="Item[@id='fur_cloak_c']"/>
	<xsl:template match="Item[@id='baggy_trunks']"/>
	<xsl:template match="Item[@id='dummy_armor_min']"/>
	<xsl:template match="Item[@id='battania_light_armor_d']"/>
	<xsl:template match="Item[@id='armored_baggy_trunks']"/>
	<xsl:template match="Item[@id='battanian_savage_armor']"/>
	<xsl:template match="Item[@id='burlap_sack_dress']"/>
	<xsl:template match="Item[@id='hemp_tunic']"/>
	<xsl:template match="Item[@id='aserai_villager_female_dress']"/>
	<xsl:template match="Item[@id='bandit_envelope_dress_v2']"/>
	<xsl:template match="Item[@id='cloth_tunic']"/>
	<xsl:template match="Item[@id='cut_dress']"/>
	<xsl:template match="Item[@id='dress_with_overall']"/>
	<xsl:template match="Item[@id='empire_dress']"/>
	<xsl:template match="Item[@id='fine_town_tunic']"/>
	<xsl:template match="Item[@id='fur_trimmed_short_tunic']"/>
	<xsl:template match="Item[@id='laced_dress']"/>
	<xsl:template match="Item[@id='long_desert_robe']"/>
	<xsl:template match="Item[@id='long_woolen_tunic']"/>
	<xsl:template match="Item[@id='monk_robe']"/>
	<xsl:template match="Item[@id='northern_dress']"/>
	<xsl:template match="Item[@id='northern_tunic']"/>
	<xsl:template match="Item[@id='plain_dress']"/>
	<xsl:template match="Item[@id='sackcloth_tunic']"/>
	<xsl:template match="Item[@id='steppe_dress']"/>
	<xsl:template match="Item[@id='steppe_robe']"/>
	<xsl:template match="Item[@id='sturgia_light_tunic']"/>
	<xsl:template match="Item[@id='torn_bandit_clothes']"/>
	<xsl:template match="Item[@id='vlandian_corset_dress']"/>
	<xsl:template match="Item[@id='vlandian_noble_woman_dress']"/>
	<xsl:template match="Item[@id='vlandian_woman_dress']"/>
	<xsl:template match="Item[@id='aserai_civil_c']"/>
	<xsl:template match="Item[@id='aserai_civil_d']"/>
	<xsl:template match="Item[@id='aserai_civil_e']"/>
	<xsl:template match="Item[@id='aserai_civil_f']"/>
	<xsl:template match="Item[@id='aserai_female_civil_b']"/>
	<xsl:template match="Item[@id='aserai_tunic_waistcoat']"/>
	<xsl:template match="Item[@id='bandit_leather_water_flask']"/>
	<xsl:template match="Item[@id='battania_civil_a']"/>
	<xsl:template match="Item[@id='burlap_waistcoat']"/>
	<xsl:template match="Item[@id='cloth_apron']"/>
	<xsl:template match="Item[@id='cut_dress_with_pouch']"/>
	<xsl:template match="Item[@id='desert_robe']"/>
	<xsl:template match="Item[@id='eastern_silk_clothing']"/>
	<xsl:template match="Item[@id='empire_dress_b']"/>
	<xsl:template match="Item[@id='fine_southern_dress']"/>
	<xsl:template match="Item[@id='half_apron']"/>
	<xsl:template match="Item[@id='nordic_tunic']"/>
	<xsl:template match="Item[@id='peasant_costume']"/>
	<xsl:template match="Item[@id='ragged_robes']"/>
	<xsl:template match="Item[@id='tassled_southern_robes']"/>
	<xsl:template match="Item[@id='tattered_rags']"/>
	<xsl:template match="Item[@id='tunic_with_shoulder_pads']"/>
	<xsl:template match="Item[@id='vlandian_dress']"/>
	<xsl:template match="Item[@id='aserai_civil_b']"/>
	<xsl:template match="Item[@id='bandit_envelope_dress_v1']"/>
	<xsl:template match="Item[@id='battania_dress_a']"/>
	<xsl:template match="Item[@id='battania_dress_b']"/>
	<xsl:template match="Item[@id='battania_dress_c']"/>
	<xsl:template match="Item[@id='battania_female_civil_a']"/>
	<xsl:template match="Item[@id='battania_female_civil_b']"/>
	<xsl:template match="Item[@id='decorated_short_tunic']"/>
	<xsl:template match="Item[@id='empire_short_dress']"/>
	<xsl:template match="Item[@id='footmans_tunic']"/>
	<xsl:template match="Item[@id='fur_skirt']"/>
	<xsl:template match="Item[@id='fur_trimmed_tunic']"/>
	<xsl:template match="Item[@id='imperial_robes']"/>
	<xsl:template match="Item[@id='khuzait_dress']"/>
	<xsl:template match="Item[@id='long_hemp_tunic']"/>
	<xsl:template match="Item[@id='thick_sleeved_robe']"/>
	<xsl:template match="Item[@id='tied_cloth_tunic']"/>
	<xsl:template match="Item[@id='tundra_tunic']"/>
	<xsl:template match="Item[@id='vlandia_bandit_c']"/>
	<xsl:template match="Item[@id='aserai_female_civil_a']"/>
	<xsl:template match="Item[@id='battania_civil_c']"/>
	<xsl:template match="Item[@id='roughcloth_shortcoat']"/>
	<xsl:template match="Item[@id='fur_skirt_with_tunic']"/>
	<xsl:template match="Item[@id='leather_apron']"/>
	<xsl:template match="Item[@id='vlandia_bandit_b']"/>
	<xsl:template match="Item[@id='sleeveless_studded_fur_armor']"/>
	<xsl:template match="Item[@id='battania_light_armor_e']"/>
	<xsl:template match="Item[@id='aserai_civil_a']"/>
	<xsl:template match="Item[@id='bandit_fur_a']"/>
	<xsl:template match="Item[@id='bandit_fur_b']"/>
	<xsl:template match="Item[@id='bandit_gambeson']"/>
	<xsl:template match="Item[@id='heavy_nordic_coat']"/>
	<xsl:template match="Item[@id='heavy_nordic_tunic']"/>
	<xsl:template match="Item[@id='merchants_fur_coat']"/>
	<xsl:template match="Item[@id='steppe_armor']"/>
	<xsl:template match="Item[@id='tunic_with_rolled_cloth']"/>
	<xsl:template match="Item[@id='dummy_armor_lower_average']"/>
	<xsl:template match="Item[@id='fur_coat_over_tunic']"/>
	<xsl:template match="Item[@id='fur_waistcoat_over_tunic']"/>
	<xsl:template match="Item[@id='khuzait_civil_coat']"/>
	<xsl:template match="Item[@id='khuzait_civil_coat_b']"/>
	<xsl:template match="Item[@id='sleeveless_fur_coat']"/>
	<xsl:template match="Item[@id='battania_civil_b']"/>
	<xsl:template match="Item[@id='khuzait_dress_b']"/>
	<xsl:template match="Item[@id='layered_robe']"/>
	<xsl:template match="Item[@id='light_tunic']"/>
	<xsl:template match="Item[@id='northern_leather_vest']"/>
	<xsl:template match="Item[@id='fur_armor_with_strap']"/>
	<xsl:template match="Item[@id='highland_cloth']"/>
	<xsl:template match="Item[@id='nordic_padded_cloth']"/>
	<xsl:template match="Item[@id='northern_padded_cloth']"/>
	<xsl:template match="Item[@id='patched_gambeson']"/>
	<xsl:template match="Item[@id='studded_leather_waistcoat']"/>
	<xsl:template match="Item[@id='vlandia_bandit_a']"/>
	<xsl:template match="Item[@id='khuzait_belt_leather']"/>
	<xsl:template match="Item[@id='battania_light_armor_c']"/>
	<xsl:template match="Item[@id='crude_leather_armor']"/>
	<xsl:template match="Item[@id='imperial_padded_cloth']"/>
	<xsl:template match="Item[@id='long_fur_coat']"/>
	<xsl:template match="Item[@id='northern_padded_gambeson']"/>
	<xsl:template match="Item[@id='padded_leather_shirt']"/>
	<xsl:template match="Item[@id='studded_fur_armor']"/>
	<xsl:template match="Item[@id='desert_padded_cloth']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_a']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_e']"/>
	<xsl:template match="Item[@id='gambeson_b']"/>
	<xsl:template match="Item[@id='leather_coat_over_cloth']"/>
	<xsl:template match="Item[@id='leather_tunic']"/>
	<xsl:template match="Item[@id='short_padded_robe']"/>
	<xsl:template match="Item[@id='stitched_leather_vest']"/>
	<xsl:template match="Item[@id='studded_steppe_leather']"/>
	<xsl:template match="Item[@id='aketon']"/>
	<xsl:template match="Item[@id='fur_armor']"/>
	<xsl:template match="Item[@id='leather_coat']"/>
	<xsl:template match="Item[@id='battania_light_armor_b']"/>
	<xsl:template match="Item[@id='battania_woodland_outfit']"/>
	<xsl:template match="Item[@id='belted_leather_cuirass']"/>
	<xsl:template match="Item[@id='layered_leather_tunic']"/>
	<xsl:template match="Item[@id='long_padded_robe']"/>
	<xsl:template match="Item[@id='rough_fur_armor']"/>
	<xsl:template match="Item[@id='khuzait_sturdy_armor']"/>
	<xsl:template match="Item[@id='studded_leather_coat']"/>
	<xsl:template match="Item[@id='khuzait_leather_stitched']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_c']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_d']"/>
	<xsl:template match="Item[@id='khuzait_fortified_armor']"/>
	<xsl:template match="Item[@id='padded_cloth_with_strips']"/>
	<xsl:template match="Item[@id='padded_leather_overcoat']"/>
	<xsl:template match="Item[@id='woven_leather_vest']"/>
	<xsl:template match="Item[@id='padded_short_coat']"/>
	<xsl:template match="Item[@id='sleeveless_padded_coat']"/>
	<xsl:template match="Item[@id='sleeveless_padded_short_coat']"/>
	<xsl:template match="Item[@id='leather_scale_armor']"/>
	<xsl:template match="Item[@id='reinforced_suede_armor']"/>
	<xsl:template match="Item[@id='nordic_sloven_leather']"/>
	<xsl:template match="Item[@id='nordic_sloven']"/>
	<xsl:template match="Item[@id='battania_light_armor_a']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_f']"/>
	<xsl:template match="Item[@id='leather_strips_over_padded_robe']"/>
	<xsl:template match="Item[@id='aserai_horseman_armor']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_g']"/>
	<xsl:template match="Item[@id='northern_leather_tabard']"/>
	<xsl:template match="Item[@id='empire_warrior_padded_armor_b']"/>
	<xsl:template match="Item[@id='basic_imperial_leather_armor']"/>
	<xsl:template match="Item[@id='leather_lamellar_armor']"/>
	<xsl:template match="Item[@id='padded_coat']"/>
	<xsl:template match="Item[@id='woven_leather_coat']"/>
	<xsl:template match="Item[@id='eastern_stitched_leather_coat']"/>
	<xsl:template match="Item[@id='eastern_studded_leather']"/>
	<xsl:template match="Item[@id='leather_and_iron_plate_armor']"/>
	<xsl:template match="Item[@id='studded_leather_over_aketon']"/>
	<xsl:template match="Item[@id='eastern_plated_leather_vest']"/>
	<xsl:template match="Item[@id='scale_armor']"/>
	<xsl:template match="Item[@id='sturgian_chainmale_shortsleeve']"/>
	<xsl:template match="Item[@id='battanian_chainmail_armor_b']"/>
	<xsl:template match="Item[@id='northern_lamellar_armor']"/>
	<xsl:template match="Item[@id='veteran_mercenary_armor']"/>
	<xsl:template match="Item[@id='nordic_lamellar_vest']"/>
	<xsl:template match="Item[@id='empire_plate_vest_armor']"/>
	<xsl:template match="Item[@id='ringed_desert_armor']"/>
	<xsl:template match="Item[@id='vlandia_chainmail']"/>
	<xsl:template match="Item[@id='battanian_chainmail_armor_a']"/>
	<xsl:template match="Item[@id='buckled_wildsman_armor']"/>
	<xsl:template match="Item[@id='khuzait_lamellar_strapped']"/>
	<xsl:template match="Item[@id='sturgian_lamellar_gambeson']"/>
	<xsl:template match="Item[@id='mail_shirt']"/>
	<xsl:template match="Item[@id='decorated_nordic_hauberk']"/>
	<xsl:template match="Item[@id='nordic_hauberk']"/>
	<xsl:template match="Item[@id='battania_woodland_chainmail']"/>
	<xsl:template match="Item[@id='imperial_mail_vest']"/>
	<xsl:template match="Item[@id='red_coat_over_mail']"/>
	<xsl:template match="Item[@id='white_coat_over_mail']"/>
	<xsl:template match="Item[@id='imperial_mail_over_stripped_leather']"/>
	<xsl:template match="Item[@id='rough_fur_over_chain']"/>
	<xsl:template match="Item[@id='ranger_mail']"/>
	<xsl:template match="Item[@id='dummy_armor_higher_average']"/>
	<xsl:template match="Item[@id='imperial_mail_over_leather']"/>
	<xsl:template match="Item[@id='nordic_sloven_over_mail']"/>
	<xsl:template match="Item[@id='stitched_leather_over_mail']"/>
	<xsl:template match="Item[@id='sturgian_lamellar_gambeson_heavy']"/>
	<xsl:template match="Item[@id='kilt_over_plated_leather']"/>
	<xsl:template match="Item[@id='aserai_armor_02']"/>
	<xsl:template match="Item[@id='battanian_chainmail_armor_c']"/>
	<xsl:template match="Item[@id='desert_robe_over_mail']"/>
	<xsl:template match="Item[@id='aserai_robe_c_chain']"/>
	<xsl:template match="Item[@id='southern_lamellar_armor']"/>
	<xsl:template match="Item[@id='western_scale_mail']"/>
	<xsl:template match="Item[@id='battanian_chainmail_armor_d']"/>
	<xsl:template match="Item[@id='banded_leather_over_mail']"/>
	<xsl:template match="Item[@id='legionary_mail']"/>
	<xsl:template match="Item[@id='aserai_armor_02_b']"/>
	<xsl:template match="Item[@id='battania_mercenary_armor']"/>
	<xsl:template match="Item[@id='empire_horseman_armor']"/>
	<xsl:template match="Item[@id='empire_legion_a']"/>
	<xsl:template match="Item[@id='aserai_brass_plate_a']"/>
	<xsl:template match="Item[@id='dummy_armor_max']"/>
	<xsl:template match="Item[@id='nordic_lamellar_armor']"/>
	<xsl:template match="Item[@id='aserai_brass_plate_b']"/>
	<xsl:template match="Item[@id='battanian_scale_armor_b']"/>
	<xsl:template match="Item[@id='eastern_plated_leather']"/>
	<xsl:template match="Item[@id='aserai_archer_armor']"/>
	<xsl:template match="Item[@id='battania_noble_armor']"/>
	<xsl:template match="Item[@id='aserai_chain_plate_armor_a']"/>
	<xsl:template match="Item[@id='aserai_chain_plate_armor_b']"/>
	<xsl:template match="Item[@id='aserai_chain_plate_armor_c']"/>
	<xsl:template match="Item[@id='aserai_chain_plate_armor_d']"/>
	<xsl:template match="Item[@id='aserai_scale_armor_on_cloth']"/>
	<xsl:template match="Item[@id='battania_brass_plate_armor']"/>
	<xsl:template match="Item[@id='plated_leather_coat']"/>
	<xsl:template match="Item[@id='eastern_lamellar_armor']"/>
	<xsl:template match="Item[@id='hauberk']"/>
	<xsl:template match="Item[@id='sturgian_chainmale_longsleeve']"/>
	<xsl:template match="Item[@id='imperial_lamellar']"/>
	<xsl:template match="Item[@id='sturgian_lamellar_base']"/>
	<xsl:template match="Item[@id='battanian_scale_armor_a']"/>
	<xsl:template match="Item[@id='coat_of_plates_over_mail']"/>
	<xsl:template match="Item[@id='sturgia_cavalry_armor']"/>
	<xsl:template match="Item[@id='empire_legion_b']"/>
	<xsl:template match="Item[@id='imperial_lamellar_over_leather']"/>
	<xsl:template match="Item[@id='northern_brass_lamellar_over_mail']"/>
	<xsl:template match="Item[@id='northern_coat_of_plates']"/>
	<xsl:template match="Item[@id='aserai_full_scale_armor_on_chain']"/>
	<xsl:template match="Item[@id='aserai_scale_armor_on_chain']"/>
	<xsl:template match="Item[@id='desert_scale_armor']"/>
	<xsl:template match="Item[@id='battania_warlord_armor']"/>
	<xsl:template match="Item[@id='brass_lamellar_over_mail']"/>
	<xsl:template match="Item[@id='sturgian_fortified_armor']"/>
	<xsl:template match="Item[@id='khuzait_heavy_armor']"/>
	<xsl:template match="Item[@id='desert_lamellar']"/>
	<xsl:template match="Item[@id='sturgian_lamellar_fortified']"/>
	<xsl:template match="Item[@id='lamellar_with_scale_skirt']"/>
	<xsl:template match="Item[@id='imperial_scale_armor']"/>
	<xsl:template match="Item[@id='rough_tied_bracers']"/>
	<xsl:template match="Item[@id='armwraps']"/>
	<xsl:template match="Item[@id='ragged_armwraps']"/>
	<xsl:template match="Item[@id='leather_gloves']"/>
	<xsl:template match="Item[@id='buttoned_leather_bracers']"/>
	<xsl:template match="Item[@id='roughtied_leather_bracers']"/>
	<xsl:template match="Item[@id='eastern_wrapped_armguards']"/>
	<xsl:template match="Item[@id='guarded_armwraps']"/>
	<xsl:template match="Item[@id='studded_vambraces']"/>
	<xsl:template match="Item[@id='strapped_leather_bracers']"/>
	<xsl:template match="Item[@id='padded_vambrace']"/>
	<xsl:template match="Item[@id='woven_leather_bracers']"/>
	<xsl:template match="Item[@id='guarded_padded_vambrace']"/>
	<xsl:template match="Item[@id='highland_gloves']"/>
	<xsl:template match="Item[@id='padded_mitten']"/>
	<xsl:template match="Item[@id='studded_leather_vambraces']"/>
	<xsl:template match="Item[@id='steppe_leather_vambraces']"/>
	<xsl:template match="Item[@id='lordly_padded_mitten']"/>
	<xsl:template match="Item[@id='reinforced_padded_mitten']"/>
	<xsl:template match="Item[@id='battania_noble_bracers']"/>
	<xsl:template match="Item[@id='reinforced_leather_vambraces']"/>
	<xsl:template match="Item[@id='northern_brass_bracers']"/>
	<xsl:template match="Item[@id='plated_strip_gauntlets']"/>
	<xsl:template match="Item[@id='eastern_plated_leather_vambraces']"/>
	<xsl:template match="Item[@id='mail_mitten']"/>
	<xsl:template match="Item[@id='reinforced_mail_mitten']"/>
	<xsl:template match="Item[@id='battania_warlord_bracers']"/>
	<xsl:template match="Item[@id='decorated_imperial_gauntlets']"/>
	<xsl:template match="Item[@id='northern_plated_gloves']"/>
	<xsl:template match="Item[@id='lordly_mail_mitten']"/>
	<xsl:template match="Item[@id='lamellar_plate_gauntlets']"/>
	<xsl:template match="Item[@id='khuzait_heavy_armor_bracer']"/>
	<xsl:template match="Item[@id='ladys_shoe']"/>
	<xsl:template match="Item[@id='southern_moccasins']"/>
	<xsl:template match="Item[@id='leather_shoes']"/>
	<xsl:template match="Item[@id='fine_town_boots']"/>
	<xsl:template match="Item[@id='sturgia_boots_d']"/>
	<xsl:template match="Item[@id='strapped_shoes']"/>
	<xsl:template match="Item[@id='sturgia_boots_c']"/>
	<xsl:template match="Item[@id='folded_town_boots']"/>
	<xsl:template match="Item[@id='turndown_leather_boots']"/>
	<xsl:template match="Item[@id='ragged_boots']"/>
	<xsl:template match="Item[@id='highland_boots']"/>
	<xsl:template match="Item[@id='sturgia_boots_a']"/>
	<xsl:template match="Item[@id='battania_woodland_boots']"/>
	<xsl:template match="Item[@id='khuzait_curved_boots']"/>
	<xsl:template match="Item[@id='empire_horseman_boots']"/>
	<xsl:template match="Item[@id='belted_leather_boots']"/>
	<xsl:template match="Item[@id='eastern_leather_boots']"/>
	<xsl:template match="Item[@id='steppe_leather_boots']"/>
	<xsl:template match="Item[@id='sturgia_boots_b']"/>
	<xsl:template match="Item[@id='highland_leg_wrappings']"/>
	<xsl:template match="Item[@id='strapped_leather_boots']"/>
	<xsl:template match="Item[@id='rough_tied_boots']"/>
	<xsl:template match="Item[@id='woven_leather_boots']"/>
	<xsl:template match="Item[@id='leather_boots']"/>
	<xsl:template match="Item[@id='battania_leather_boots']"/>
	<xsl:template match="Item[@id='leather_cavalier_boots']"/>
	<xsl:template match="Item[@id='wrapped_leather_boots']"/>
	<xsl:template match="Item[@id='battania_fur_boots']"/>
	<xsl:template match="Item[@id='wrapped_shoes']"/>
	<xsl:template match="Item[@id='reinforced_suede_boots']"/>
	<xsl:template match="Item[@id='mail_chausses']"/>
	<xsl:template match="Item[@id='plated_strip_boots']"/>
	<xsl:template match="Item[@id='mail_cavalier_boots']"/>
	<xsl:template match="Item[@id='strapped_mail_chausses']"/>
	<xsl:template match="Item[@id='decorated_imperial_boots']"/>
	<xsl:template match="Item[@id='battania_warlord_boots']"/>
	<xsl:template match="Item[@id='northern_plated_boots']"/>
	<xsl:template match="Item[@id='lamellar_plate_boots']"/>
	<!-- #endregion -->
	<!-- region native horses -->
	<xsl:template match="Item[@id='sumpter_horse']"/>
	<xsl:template match="Item[@id='old_horse']"/>
	<xsl:template match="Item[@id='mule']"/>
	<xsl:template match="Item[@id='mule_unmountable']"/>
	<xsl:template match="Item[@id='pack_camel']"/>
	<xsl:template match="Item[@id='pack_camel_unmountable']"/>
	<xsl:template match="Item[@id='aserai_horse']"/>
	<xsl:template match="Item[@id='battania_horse']"/>
	<xsl:template match="Item[@id='empire_horse']"/>
	<xsl:template match="Item[@id='khuzait_horse']"/>
	<xsl:template match="Item[@id='sturgia_horse']"/>
	<xsl:template match="Item[@id='vlandia_horse']"/>
	<xsl:template match="Item[@id='camel']"/>
	<xsl:template match="Item[@id='saddle_horse']"/>
	<xsl:template match="Item[@id='t2_aserai_horse']"/>
	<xsl:template match="Item[@id='t2_battania_horse']"/>
	<xsl:template match="Item[@id='t2_empire_horse']"/>
	<xsl:template match="Item[@id='t2_khuzait_horse']"/>
	<xsl:template match="Item[@id='t2_sturgia_horse']"/>
	<xsl:template match="Item[@id='t2_vlandia_horse']"/>
	<xsl:template match="Item[@id='war_camel']"/>
	<xsl:template match="Item[@id='hunter']"/>
	<xsl:template match="Item[@id='charger']"/>
	<xsl:template match="Item[@id='t3_aserai_horse']"/>
	<xsl:template match="Item[@id='t3_battania_horse']"/>
	<xsl:template match="Item[@id='t3_empire_horse']"/>
	<xsl:template match="Item[@id='t3_khuzait_horse']"/>
	<xsl:template match="Item[@id='t3_sturgia_horse']"/>
	<xsl:template match="Item[@id='t3_vlandia_horse']"/>
	<xsl:template match="Item[@id='noble_camel']"/>
	<xsl:template match="Item[@id='noble_horse_southern']"/>
	<xsl:template match="Item[@id='noble_horse_imperial']"/>
	<xsl:template match="Item[@id='noble_horse_eastern']"/>
	<xsl:template match="Item[@id='noble_horse_northern']"/>
	<xsl:template match="Item[@id='noble_horse_western']"/>
	<xsl:template match="Item[@id='special_camel']"/>
	<xsl:template match="Item[@id='noble_horse_battania']"/>
	<xsl:template match="Item[@id='noble_horse_khamseen']"/>
	<xsl:template match="Item[@id='noble_horse']"/>
	<xsl:template match="Item[@id='storm_charger']"/>
	<xsl:template match="Item[@id='war_horse']"/>
	<xsl:template match="Item[@id='steppe_war_horse']"/>
	<xsl:template match="Item[@id='desert_war_horse']"/>
	<xsl:template match="Item[@id='aserai_horse_tournament']"/>
	<xsl:template match="Item[@id='battania_horse_tournament']"/>
	<xsl:template match="Item[@id='empire_horse_tournament']"/>
	<xsl:template match="Item[@id='khuzait_horse_tournament']"/>
	<xsl:template match="Item[@id='sturgia_horse_tournament']"/>
	<xsl:template match="Item[@id='vlandia_horse_tournament']"/>
	<xsl:template match="Item[@id='camel_tournament']"/>
	<xsl:template match="Item[@id='bandit_saddle_desert']"/>
	<xsl:template match="Item[@id='bandit_saddle_steppe']"/>
	<xsl:template match="Item[@id='bandit_saddle_highland']"/>
	<xsl:template match="Item[@id='light_harness']"/>
	<xsl:template match="Item[@id='halfchain_barding']"/>
	<xsl:template match="Item[@id='celtic_frost']"/>
	<xsl:template match="Item[@id='chain_barding']"/>
	<xsl:template match="Item[@id='chain_horse_harness']"/>
	<xsl:template match="Item[@id='stripped_leather_harness']"/>
	<xsl:template match="Item[@id='imperial_riding_harness']"/>
	<xsl:template match="Item[@id='half_scale_barding']"/>
	<xsl:template match="Item[@id='imperial_scale_barding']"/>
	<xsl:template match="Item[@id='studded_steppe_barding']"/>
	<xsl:template match="Item[@id='desert_cloth_harness']"/>
	<xsl:template match="Item[@id='aseran_village_harness']"/>
	<xsl:template match="Item[@id='half_mail_and_plate_barding']"/>
	<xsl:template match="Item[@id='mail_and_plate_barding']"/>
	<xsl:template match="Item[@id='steppe_harness']"/>
	<xsl:template match="Item[@id='steppe_fur_harness']"/>
	<xsl:template match="Item[@id='steppe_half_barding']"/>
	<xsl:template match="Item[@id='northern_light_harness']"/>
	<xsl:template match="Item[@id='northern_noble_harness']"/>
	<xsl:template match="Item[@id='northern_ring_barding']"/>
	<xsl:template match="Item[@id='battania_horse_harness']"/>
	<xsl:template match="Item[@id='battania_horse_harness_halfscaled']"/>
	<xsl:template match="Item[@id='battania_horse_harness_scaled']"/>
	<xsl:template match="Item[@id='camel_saddle']"/>
	<xsl:template match="Item[@id='camel_saddle_a']"/>
	<xsl:template match="Item[@id='camel_saddle_b']"/>
	<xsl:template match="Item[@id='fortunas_choice']"/>
	<xsl:template match="Item[@id='saddle_of_aeneas']"/>
	<xsl:template match="Item[@id='mule_load_a']"/>
	<xsl:template match="Item[@id='mule_load_b']"/>
	<xsl:template match="Item[@id='mule_load_c']"/>
	<!-- #endregion -->
	<!-- region native misc -->
	<xsl:template match="Item[@id='stolen_goods']"/>
	<!-- #endregion -->
	<!-- region native weapons -->
	<xsl:template match="CraftedItem[@id='sturgia_lance_2_t5']"/>
	<xsl:template match="CraftedItem[@id='sturgia_lance_1_t4']"/>
	<xsl:template match="CraftedItem[@id='khuzait_lance_1_t3']"/>
	<xsl:template match="CraftedItem[@id='khuzait_lance_2_t4']"/>
	<xsl:template match="CraftedItem[@id='vlandia_lance_3_t5']"/>
	<xsl:template match="CraftedItem[@id='vlandia_lance_2_t4']"/>
	<xsl:template match="CraftedItem[@id='vlandia_lance_1_t3']"/>
	<xsl:template match="CraftedItem[@id='battania_2hsword_5_t4']"/>
	<!-- #endregion -->
	<!-- region shields-->
	<xsl:template match="CraftedItem[@id='adarga']"/>
	<xsl:template match="CraftedItem[@id='bound_desert_round_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='bound_adarga']"/>
	<xsl:template match="CraftedItem[@id='bound_desert_round_shield']"/>
	<xsl:template match="CraftedItem[@id='studded_adarga']"/>
	<xsl:template match="CraftedItem[@id='large_adarga']"/>
	<xsl:template match="CraftedItem[@id='ornate_adarga']"/>
	<xsl:template match="CraftedItem[@id='studded_round_shield']"/>
	<xsl:template match="CraftedItem[@id='steel_round_shield']"/>
	<xsl:template match="CraftedItem[@id='decorated_steppe_shield']"/>
	<xsl:template match="CraftedItem[@id='steppe_guardian_shield']"/>
	<xsl:template match="CraftedItem[@id='tribal_steppe_shield']"/>
	<xsl:template match="CraftedItem[@id='noyans_shield']"/>
	<xsl:template match="CraftedItem[@id='highland_scouts_shield']"/>
	<xsl:template match="CraftedItem[@id='highland_riders_shield']"/>
	<xsl:template match="CraftedItem[@id='horsemans_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='curved_round_shield']"/>
	<xsl:template match="CraftedItem[@id='small_flat_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='small_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='battania_targe_b']"/>
	<xsl:template match="CraftedItem[@id='battania_shield_targe_a']"/>
	<xsl:template match="CraftedItem[@id='battania_large_shield_c']"/>
	<xsl:template match="CraftedItem[@id='battania_large_shield_a']"/>
	<xsl:template match="CraftedItem[@id='battania_large_shield_b']"/>
	<xsl:template match="CraftedItem[@id='northern_round_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='sturgia_old_shield_b']"/>
	<xsl:template match="CraftedItem[@id='northern_round_shield']"/>
	<xsl:template match="CraftedItem[@id='desert_round_shield']"/>
	<xsl:template match="CraftedItem[@id='sturgia_old_shield_c']"/>
	<xsl:template match="CraftedItem[@id='viking_round_shield']"/>
	<xsl:template match="CraftedItem[@id='leather_round_shield']"/>
	<xsl:template match="CraftedItem[@id='strapped_round_shield']"/>
	<xsl:template match="CraftedItem[@id='heavy_round_shield']"/>
	<xsl:template match="CraftedItem[@id='sturgia_old_shield_a']"/>
	<xsl:template match="CraftedItem[@id='battered_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='old_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='worn_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='light_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='bound_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='reinforced_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='northern_scouts_shield']"/>
	<xsl:template match="CraftedItem[@id='northern_horsemans_shield']"/>
	<xsl:template match="CraftedItem[@id='heavy_horsemans_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='heater_shield_with_cutout']"/>
	<xsl:template match="CraftedItem[@id='western_riders_kite_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='western_riders_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='ironrim_riders_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='eastern_wicker_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='eastern_wicker_shield']"/>
	<xsl:template match="CraftedItem[@id='flat_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='stronger_eastern_wicker_shield']"/>
	<xsl:template match="CraftedItem[@id='wide_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='jousting_shield']"/>
	<xsl:template match="CraftedItem[@id='footmans_wicker_shield']"/>
	<xsl:template match="CraftedItem[@id='stronger_footmans_wicker_shield']"/>
	<xsl:template match="CraftedItem[@id='bracketed_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='heavy_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='tall_heater_shield']"/>
	<xsl:template match="CraftedItem[@id='battered_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='western_kite_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='ironrim_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='reinforced_flat_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='western_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='studded_bound_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='fortified_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='chivalric_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='desert_oval_shield']"/>
	<xsl:template match="CraftedItem[@id='southern_oval_shield']"/>
	<xsl:template match="CraftedItem[@id='emirs_oval_shield']"/>
	<xsl:template match="CraftedItem[@id='pavise_shield']"/>
	<xsl:template match="CraftedItem[@id='worn_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='leather_bound_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='reinforced_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='stronger_reinforced_kite_shield']"/>
	<xsl:template match="CraftedItem[@id='oval_shield']"/>
	<xsl:template match="CraftedItem[@id='old_kite_sparring_shield']"/>
	<xsl:template match="CraftedItem[@id='old_kite_shield']"/>
	<!-- #endregion -->
	<!-- #region Shoulder shields -->
	<xsl:template match="CraftedItem[@id='battania_shield_targe_a_shoulder']"/>
	<xsl:template match="CraftedItem[@id='decorated_steppe_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='steppe_guardian_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='tribal_steppe_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='noyans_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='horsemans_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='small_flat_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='small_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='battered_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='old_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='worn_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='light_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='bound_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='reinforced_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='northern_scouts_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='northern_horsemans_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='heavy_horsemans_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='heater_shield_with_cutout_shoulder']"/>
	<xsl:template match="CraftedItem[@id='western_riders_kite_sparring_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='western_riders_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='ironrim_riders_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='flat_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='wide_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='jousting_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='bracketed_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='heavy_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='tall_heater_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='battered_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='western_kite_sparring_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='ironrim_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='reinforced_flat_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='western_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='studded_bound_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='fortified_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='chivalric_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='pavise_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='worn_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='leather_bound_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='reinforced_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='stronger_reinforced_kite_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='old_kite_sparring_shield_shoulder']"/>
	<xsl:template match="CraftedItem[@id='old_kite_shield_shoulder']"/>
	<!-- #endregion -->
	<!-- BL 1.3.1 -->
	<xsl:template match="Item[@id='assassin_armor']"/>
	<xsl:template match="Item[@id='assassin_hood']"/>
	<xsl:template match="Item[@id='assassin_boot']"/>
	<xsl:template match="Item[@id='assassin_shoulder']"/>
	
	
	
</xsl:stylesheet>