<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_vlandia']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_battania']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_khuzait']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_empire']"/>
     
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_sturgia']"/>
	
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_default_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_0_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_1_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_1_page_2_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_default_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_child_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_0_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_child_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_1_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_child_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_2_page_2_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_default_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_0_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_1_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_3_page_2_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_default_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_0_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_1_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_4_page_2_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_default_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_0_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_1_branch_5_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_1_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_2_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_3_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_4_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_education_equipments_stage_5_page_2_branch_5_aserai']"/>
	
	</xsl:stylesheet>