<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- region OSA_aom_bip_armor -->
	<xsl:template match="Item[@id='ao_durkhan_tassled_necklace']"/>
	<xsl:template match="Item[@id='ao_generic_short_cape']"/>
	<xsl:template match="Item[@id='ao_focale']"/>
	<xsl:template match="Item[@id='ao_battanian_cloak']"/>
	<xsl:template match="Item[@id='ao_battanian_medallion']"/>
	<xsl:template match="Item[@id='ao_caladogs_medallion']"/>
	<xsl:template match="Item[@id='ao_imperial_noblemans_sash']"/>
	<xsl:template match="Item[@id='ao_light_fur_shoulder']"/>
	<xsl:template match="Item[@id='ao_battanian_mail_shoulders']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_a']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_a2']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_b']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_c']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_d']"/>
	<xsl:template match="Item[@id='AO_aserai_shoulders_d2']"/>
	<xsl:template match="Item[@id='ao_imperial_decorated_bracers']"/>
	<xsl:template match="Item[@id='ao_imperial_decorated_bracers_b']"/>
	<xsl:template match="Item[@id='AO_durkhan_gauntlets_a']"/>
	<xsl:template match="Item[@id='AO_durkhan_gauntlets_b']"/>
	<xsl:template match="Item[@id='ao_durkhan_tassled_boots']"/>
	<xsl:template match="Item[@id='AO_durkhan_boots_b']"/>
	<xsl:template match="Item[@id='AO_durkhan_boots_c']"/>
	<xsl:template match="Item[@id='ao_leather_shoes']"/>
	<xsl:template match="Item[@id='ao_battanian_hauberk_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_mail_shirt_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_gambeson']"/>
	<xsl:template match="Item[@id='ao_battanian_gambeson_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_scale_armor']"/>
	<xsl:template match="Item[@id='ao_battanian_cloth_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_woolen_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_bronze_scale_over_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_iron_scale_over_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_alt_scale_over_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_leather_tunic_with_kilt']"/>
	<xsl:template match="Item[@id='ao_battanian_decorated_scale_armor']"/>
	<xsl:template match="Item[@id='ao_battanian_decorated_scale_armor_b']"/>
	<xsl:template match="Item[@id='ao_battanian_decorated_scale_armor_c']"/>
	<xsl:template match="Item[@id='ao_durkhan_hide_poncho']"/>
	<xsl:template match="Item[@id='ao_durkhan_tunic']"/>
	<xsl:template match="Item[@id='ao_durkhan_trousers']"/>
	<xsl:template match="Item[@id='ao_durkhan_leather_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_sleeveless_leather_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_chestplate']"/>
	<xsl:template match="Item[@id='ao_durkhan_topless_leather_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_light_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_lamellar_thighguard']"/>
	<xsl:template match="Item[@id='ao_durkhan_heavy_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_nobles_lamellar']"/>
	<xsl:template match="Item[@id='ao_durkhan_lamellar_with_mail']"/>
	<xsl:template match="Item[@id='ao_eorling_plates_over_mail']"/>
	<xsl:template match="Item[@id='ao_eorling_plates_over_gambeson']"/>
	<xsl:template match="Item[@id='ao_eorling_bronze_scale_over_mail']"/>
	<xsl:template match="Item[@id='ao_eorling_iron_scale_over_mail']"/>
	<xsl:template match="Item[@id='AO_eorling_armor_d']"/>
	<xsl:template match="Item[@id='AO_eorling_armor_d2']"/>
	<xsl:template match="Item[@id='ao_gen_sleeveless_leather_tunic']"/>
	<xsl:template match="Item[@id='ao_gen_gambeson_over_mail']"/>
	<xsl:template match="Item[@id='ao_crude_mail_with_tunic']"/>
	<xsl:template match="Item[@id='ao_imperial_southern_scale_armor_over_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_southern_scale_armor_over_mail_b']"/>
	<xsl:template match="Item[@id='ao_imperial_lamellar_vest']"/>
	<xsl:template match="Item[@id='ao_imperial_lamellar_vest_b']"/>
	<xsl:template match="Item[@id='ao_imperial_lamellar_vest_over_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_lamellar_vest_over_mail_b']"/>
	<xsl:template match="Item[@id='ao_imperial_cataphracts_lamellar']"/>
	<xsl:template match="Item[@id='ao_imperial_cataphracts_lamellar_b']"/>
	<xsl:template match="Item[@id='AO_imperial_scouts_tunic']"/>
	<xsl:template match="Item[@id='ao_imperial_brass_scale_armor']"/>
	<xsl:template match="Item[@id='ao_imperial_brass_scale_armor_b']"/>
	<xsl:template match="Item[@id='ao_imperial_light_leather']"/>
	<xsl:template match="Item[@id='ao_sturgian_lamellar_vest']"/>
	<xsl:template match="Item[@id='ao_sturgian_lamellar_vest_b']"/>
	<xsl:template match="Item[@id='ao_sturgian_leather_over_mail']"/>
	<xsl:template match="Item[@id='ao_sturgian_leather_over_cloth']"/>
	<xsl:template match="Item[@id='ao_sturgia_armor_d']"/>
	<xsl:template match="Item[@id='ao_sturgia_armor_d2']"/>
	<xsl:template match="Item[@id='ao_khuzait_leather_vest']"/>
	<xsl:template match="Item[@id='ao_nordic_sloven_mail_sleeveless']"/>
	<xsl:template match="Item[@id='ao_sleeveless_mail_hauberk']"/>
	<xsl:template match="Item[@id='ao_mail_shirt_sleeveless']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_skirt']"/>
	<xsl:template match="Item[@id='ao_mabili_leopard_skirt']"/>
	<xsl:template match="Item[@id='ao_mabili_zebra_skirt']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_a']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_a2']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_a3']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_b']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_b2']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_b3']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_c']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_c2']"/>
	<xsl:template match="Item[@id='ao_mabili_hide_armor_c3']"/>
	<xsl:template match="Item[@id='ao_vlandian_tabard_over_aketon']"/>
	<xsl:template match="Item[@id='ao_vlandian_tabard_over_aketon_b']"/>
	<xsl:template match="Item[@id='AO_vlandia_armor_c']"/>
	<xsl:template match="Item[@id='AO_aserai_armor_a']"/>
	<xsl:template match="Item[@id='AO_aserai_armor_b']"/>
	<xsl:template match="Item[@id='AO_aserai_armor_c']"/>
	<xsl:template match="Item[@id='AO_aserai_armor_d']"/>
	<!-- #endregion -->
	<!-- region OSA_aom_bip_head -->
	<xsl:template match="Item[@id='ao_crown_a']"/>
	<xsl:template match="Item[@id='ao_crown_b']"/>
	<xsl:template match="Item[@id='ao_gold_circlet_a']"/>
	<xsl:template match="Item[@id='ao_angevin_crown']"/>
	<xsl:template match="Item[@id='ao_mabili_feathered_headband']"/>
	<xsl:template match="Item[@id='ao_mabili_leather_headband']"/>
	<xsl:template match="Item[@id='ao_crowned_mail_coif_b']"/>
	<xsl:template match="Item[@id='ao_mailed_angevin_crown']"/>
	<xsl:template match="Item[@id='ao_subuwari_helmet_a']"/>
	<xsl:template match="Item[@id='ao_subuwari_helmet_a2']"/>
	<xsl:template match="Item[@id='ao_subuwari_noblemans_helmet']"/>
	<xsl:template match="Item[@id='ao_subuwari_noblemans_helmet_b']"/>
	<xsl:template match="Item[@id='ao_vlandian_nasal_helmet_with_mail_coif']"/>
	<xsl:template match="Item[@id='ao_zhonghai_cavalry_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_fur_trimmed_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_cataphract_helmet_a']"/>
	<xsl:template match="Item[@id='ao_durkhan_cataphract_helmet_b']"/>
	<xsl:template match="Item[@id='ao_durkhan_iron_horsehair_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_guarded_iron_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_iron_lamellar_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_heavy_lamellar_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_guarded_bronze_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_horsehair_noble_bronze_helmet']"/>
	<xsl:template match="Item[@id='ao_durkhan_iron_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ao_durkhan_iron_helmet_with_leather_spiked']"/>
	<xsl:template match="Item[@id='ao_durkhan_heavy_fur_trimmed_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_riveted_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_mailed_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_guarded_noblemans_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_guarded_noblemans_helmet_b']"/>
	<xsl:template match="Item[@id='ao_eorling_heavy_guarded_noblemans_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_heavy_guarded_noblemans_helmet_a']"/>
	<xsl:template match="Item[@id='ao_eorling_heavy_guarded_noblemans_helmet_b']"/>
	<xsl:template match="Item[@id='ao_eorling_heavy_guarded_noblemans_helmet_c']"/>
	<xsl:template match="Item[@id='ao_eorling_dunheres_crowned_helmet']"/>
	<xsl:template match="Item[@id='ao_eorling_guarded_nasal_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ao_eorling_guarded_nasal_helmet_with_mail']"/>
	<xsl:template match="Item[@id='ao_eorling_guarded_nasal_helmet_with_closed_mail']"/>
	<xsl:template match="Item[@id='ao_eorling_guardian_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_spangenhelm_with_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_nasal_spangenhelmet_with_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_spangenhelm_with_leather']"/>
	<xsl:template match="Item[@id='ao_imperial_spangenhelm_over_padded_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_heavy_spangenhelm_with_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_heavy_spangenhelm_with_leather']"/>
	<xsl:template match="Item[@id='ao_imperial_nasal_helmet_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_heavy_spangenhelm_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_heavy_nasal_spangenhelm_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_redcrest_bronze_spangenhelm_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_conical_nasal_helmet_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_guarded_conical_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_kettlehelm_with_leather']"/>
	<xsl:template match="Item[@id='ao_imperial_kettlehelm_with_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_kettlehelm_over_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_crowned_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_cataphracts_closed_mail_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_cataphracts_plumed_closed_mail_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_cataphracts_flamboyant_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_evocati_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_closed_mail_nasal_spangenhelmet']"/>
	<xsl:template match="Item[@id='ao_imperial_guarded_decorated_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_nasal_spangenhelm_with_leather_strips_alt']"/>
	<xsl:template match="Item[@id='ao_imperial_nasal_spangenhelm_with_leather_strips']"/>
	<xsl:template match="Item[@id='ao_imperial_palatine_guard_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_pointed_helmet_with_lamellar_strips']"/>
	<xsl:template match="Item[@id='ao_imperial_pointed_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ao_imperial_pointed_helmet_with_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_pointed_helmet_with_cloth_wrap']"/>
	<xsl:template match="Item[@id='ao_imperial_cone_helmet_with_closed_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_plumed_cone_helmet_with_closed_mail']"/>
	<xsl:template match="Item[@id='ao_imperial_cone_helmet_with_mail_coif']"/>
	<xsl:template match="Item[@id='ao_imperial_noblemans_cone_helmet']"/>
	<xsl:template match="Item[@id='ao_imperial_cone_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ao_imperial_cone_helmet_with_lamellar_strips']"/>
	<xsl:template match="Item[@id='ao_imperial_aristocrats_helmet']"/>
	<xsl:template match="Item[@id='AO_empire_lord_helmet_k']"/>
	<xsl:template match="Item[@id='AO_empire_helmet_za']"/>
	<xsl:template match="Item[@id='AO_empire_helmet_zb']"/>
	<xsl:template match="Item[@id='ao_battanian_hood']"/>
	<xsl:template match="Item[@id='ao_battanian_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_nasal_helmet_with_neckguard']"/>
	<xsl:template match="Item[@id='ao_battanian_nasal_spangenhelm']"/>
	<xsl:template match="Item[@id='ao_battanian_segmented_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_noblemans_ridge_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_plumed_noblemans_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_noblemans_plumed_ridge_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_guarded_segmented_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_noblemans_guarded_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_noblemans_cone_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_guarded_spangenhelmet']"/>
	<xsl:template match="Item[@id='ao_battanian_guarded_aristocrats_helmet']"/>
	<xsl:template match="Item[@id='ao_battanian_guarded_aristocrats_spangenhelmet']"/>
	<xsl:template match="Item[@id='ao_battanian_guarded_aristocrats_spangenhelmet_crest']"/>
	<xsl:template match="Item[@id='ao_battanian_crowned_helmet']"/>
	<xsl:template match="Item[@id='ao_sturgian_feathered_helmet']"/>
	<xsl:template match="Item[@id='ao_sturgian_feathered_helmet_closed']"/>
	<xsl:template match="Item[@id='ao_sturgian_feathered_helmet_with_mail']"/>
	<xsl:template match="Item[@id='ao_sturgian_feathered_helmet_with_closed_mail']"/>
	<xsl:template match="Item[@id='ao_sturgian_spiked_nasal_helmet']"/>
	<xsl:template match="Item[@id='ao_sturgian_helmet_with_leather']"/>
	<xsl:template match="Item[@id='ao_sturgian_spangenhelm_with_leather']"/>
	<xsl:template match="Item[@id='ao_sturgian_pointed_helmet_with_ring']"/>
	<!-- #endregion -->
	<!-- region OSA_ap_armorpack_items -->
	<xsl:template match="Item[@id='mercenary_padding_cape']"/>
	<xsl:template match="Item[@id='heavy_samurai_shoulder']"/>
	<xsl:template match="Item[@id='leather_shoulder_a']"/>
	<xsl:template match="Item[@id='leather_shoulder_b']"/>
	<xsl:template match="Item[@id='kaftan']"/>
	<xsl:template match="Item[@id='mercenary_gambeson']"/>
	<xsl:template match="Item[@id='mercenary_mail_armor']"/>
	<xsl:template match="Item[@id='AP_leather_tabard_a']"/>
	<xsl:template match="Item[@id='leather_tabard_over_mail']"/>
	<xsl:template match="Item[@id='AP_leather_tabard_c']"/>
	<xsl:template match="Item[@id='AP_leather_tabard_d']"/>
	<xsl:template match="Item[@id='heavy_samutai']"/>
	<xsl:template match="Item[@id='mirror_armor']"/>
	<xsl:template match="Item[@id='southern_helmet_with_band']"/>
	<xsl:template match="Item[@id='southern_cone_helmet']"/>
	<xsl:template match="Item[@id='southern_heavy_helmet']"/>
	<xsl:template match="Item[@id='southern_heavy_tuareg']"/>
	<xsl:template match="Item[@id='saracen_helmet_c']"/>
	<xsl:template match="Item[@id='southern_lord_helmet_a']"/>
	<xsl:template match="Item[@id='southern_lord_helmet_b']"/>
	<xsl:template match="Item[@id='aserai_light_helmet']"/>
	<xsl:template match="Item[@id='southern_light_helmet_a']"/>
	<xsl:template match="Item[@id='aserai_mail_helmet']"/>
	<xsl:template match="Item[@id='saracen_helmet_d']"/>
	<xsl:template match="Item[@id='saracen_helmet_d_ii']"/>
	<xsl:template match="Item[@id='southern_helmet_IIII']"/>
	<xsl:template match="Item[@id='southern_heavy_helmet_with_feather']"/>
	<xsl:template match="Item[@id='sloven_hat']"/>
	<xsl:template match="Item[@id='sloven_hat_a']"/>
	<xsl:template match="Item[@id='sloven_helmet']"/>
	<xsl:template match="Item[@id='green_hat']"/>
	<xsl:template match="Item[@id='vlandia_helmet_s_ii']"/>
	<xsl:template match="Item[@id='vlandia_helmet_s_iii']"/>
	<!-- #endregion -->
	<!-- region OSA_ar_reforms_body -->
	<xsl:template match="Item[@id='AR_aserai_armor_a']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_b']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_c']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_d']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_d2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_e']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_e2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_f']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_f2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_g']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_g2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_h']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_i']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_j']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_k']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_l']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_m']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_n']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_o']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_p']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_q']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_r']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_s']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_t']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_t2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_u']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_u2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_v']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_v2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_w']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_w2']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_x']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_y']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_z']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_za']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_zb']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_zc']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_zd']"/>
	<xsl:template match="Item[@id='AR_aserai_armor_zd2']"/>
	<xsl:template match="Item[@id='AR_aserai_lamellar_a']"/>
	<xsl:template match="Item[@id='AR_aserai_lamellar_b']"/>
	<xsl:template match="Item[@id='AR_aserai_leather_a']"/>
	<xsl:template match="Item[@id='AR_aserai_scale_armor_a']"/>
	<xsl:template match="Item[@id='AR_aserai_scale_armor_b']"/>
	<xsl:template match="Item[@id='AR_aserai_scale_armor_c']"/>
	<xsl:template match="Item[@id='AR_battania_armor_a']"/>
	<xsl:template match="Item[@id='AR_battania_armor_a2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_b']"/>
	<xsl:template match="Item[@id='AR_battania_armor_b2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_c']"/>
	<xsl:template match="Item[@id='AR_battania_armor_d']"/>
	<xsl:template match="Item[@id='AR_battania_armor_e']"/>
	<xsl:template match="Item[@id='AR_battania_armor_f']"/>
	<xsl:template match="Item[@id='AR_battania_armor_g']"/>
	<xsl:template match="Item[@id='AR_battania_armor_h']"/>
	<xsl:template match="Item[@id='AR_battania_armor_i']"/>
	<xsl:template match="Item[@id='AR_battania_armor_j']"/>
	<xsl:template match="Item[@id='AR_battania_armor_k']"/>
	<xsl:template match="Item[@id='AR_battania_armor_l']"/>
	<xsl:template match="Item[@id='AR_battania_armor_m']"/>
	<xsl:template match="Item[@id='AR_battania_armor_m2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_n']"/>
	<xsl:template match="Item[@id='AR_battania_armor_n2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_o']"/>
	<xsl:template match="Item[@id='AR_battania_armor_o2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_p']"/>
	<xsl:template match="Item[@id='AR_battania_armor_p2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_p3']"/>
	<xsl:template match="Item[@id='AR_battania_armor_q']"/>
	<xsl:template match="Item[@id='AR_battania_armor_q2']"/>
	<xsl:template match="Item[@id='AR_battania_armor_q3']"/>
	<xsl:template match="Item[@id='AR_empire_armor_a']"/>
	<xsl:template match="Item[@id='AR_empire_armor_b']"/>
	<xsl:template match="Item[@id='AR_empire_armor_c']"/>
	<xsl:template match="Item[@id='AR_empire_armor_d']"/>
	<xsl:template match="Item[@id='AR_empire_armor_e']"/>
	<xsl:template match="Item[@id='AR_empire_armor_f']"/>
	<xsl:template match="Item[@id='AR_empire_armor_g']"/>
	<xsl:template match="Item[@id='AR_empire_armor_h']"/>
	<xsl:template match="Item[@id='AR_empire_armor_i']"/>
	<xsl:template match="Item[@id='AR_empire_armor_j']"/>
	<xsl:template match="Item[@id='AR_empire_armor_k']"/>
	<xsl:template match="Item[@id='AR_empire_armor_l']"/>
	<xsl:template match="Item[@id='AR_empire_armor_m']"/>
	<xsl:template match="Item[@id='AR_empire_armor_n']"/>
	<xsl:template match="Item[@id='AR_empire_armor_o']"/>
	<xsl:template match="Item[@id='AR_empire_armor_p']"/>
	<xsl:template match="Item[@id='AR_empire_armor_q']"/>
	<xsl:template match="Item[@id='AR_empire_armor_r']"/>
	<xsl:template match="Item[@id='AR_empire_armor_s']"/>
	<xsl:template match="Item[@id='AR_empire_armor_t']"/>
	<xsl:template match="Item[@id='AR_empire_brass_lamellar_a']"/>
	<xsl:template match="Item[@id='AR_empire_brass_lamellar_b']"/>
	<xsl:template match="Item[@id='AR_empire_brass_lamellar_c']"/>
	<xsl:template match="Item[@id='AR_empire_brass_lamellar_d']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor_a']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor_a2']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor_b']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor_c']"/>
	<xsl:template match="Item[@id='AR_empire_horseman_armor_d']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_a']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_b']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_c']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_d']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_e']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_e2']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_e3']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_f']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_g']"/>
	<xsl:template match="Item[@id='AR_empire_scale_armor_h']"/>
	<xsl:template match="Item[@id='AR_empire_scout_armor_a']"/>
	<xsl:template match="Item[@id='AR_empire_scout_armor_b']"/>
	<xsl:template match="Item[@id='AR_empire_scout_armor_c']"/>
	<xsl:template match="Item[@id='AR_empire_scout_armor_d']"/>
	<xsl:template match="Item[@id='AR_khuzait_armor_a']"/>
	<xsl:template match="Item[@id='AR_khuzait_armor_b']"/>
	<xsl:template match="Item[@id='AR_merchants_coat_a']"/>
	<xsl:template match="Item[@id='AR_monk_robe_a']"/>
	<xsl:template match="Item[@id='AR_monk_robe_a2']"/>
	<xsl:template match="Item[@id='AR_monk_robe_b']"/>
	<xsl:template match="Item[@id='AR_monk_robe_c']"/>
	<xsl:template match="Item[@id='AR_monk_robe_c2']"/>
	<xsl:template match="Item[@id='AR_monk_robe_d']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_a']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_b']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_c']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_d']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_d2']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_e']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_e2']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_f']"/>
	<xsl:template match="Item[@id='AR_sturgia_armor_f2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_a2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_b']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_c']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_d']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_d2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_e']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_f']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_g']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_h']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_h2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_i']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_j']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_k']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_l']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_m']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_n']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_o']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_p']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_p2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_q']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_q2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_r']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_r2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_s']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_s2']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_t']"/>
	<xsl:template match="Item[@id='AR_vlandia_armor_u']"/>
	<xsl:template match="Item[@id='AR_vlandia_lamellar_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_lamellar_a2']"/>
	<xsl:template match="Item[@id='AR_vlandia_lamellar_b']"/>
	<xsl:template match="Item[@id='AR_vlandia_leather_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_scale_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_scale_b']"/>
	<xsl:template match="Item[@id='AR_bandit_armor_a']"/>
	<!-- #endregion -->
	<!-- region OSA_ar_reforms_head-->
	<xsl:template match="Item[@id='AR_roman_hat_a']"/>
	<xsl:template match="Item[@id='AR_roman_hat_a2']"/>
	<xsl:template match="Item[@id='AR_roman_hat_b']"/>
	<xsl:template match="Item[@id='AR_roman_hat_b2']"/>
	<xsl:template match="Item[@id='AR_roman_hat_c']"/>
	<xsl:template match="Item[@id='AR_roman_hat_d']"/>
	<xsl:template match="Item[@id='AR_roman_hat_e']"/>
	<xsl:template match="Item[@id='AR_roman_hat_f']"/>
	<xsl:template match="Item[@id='AR_phrygian_cap_a']"/>
	<xsl:template match="Item[@id='AR_phrygian_cap_b']"/>
	<xsl:template match="Item[@id='AR_sturgia_womens_hat_a']"/>
	<xsl:template match="Item[@id='AR_hat_a']"/>
	<xsl:template match="Item[@id='AR_hat_b']"/>
	<xsl:template match="Item[@id='AR_hat_c']"/>
	<xsl:template match="Item[@id='AR_hat_d']"/>
	<xsl:template match="Item[@id='AR_hat_e']"/>
	<xsl:template match="Item[@id='AR_hat_f']"/>
	<xsl:template match="Item[@id='AR_hat_g']"/>
	<xsl:template match="Item[@id='AR_hat_h']"/>
	<xsl:template match="Item[@id='AR_hat_i']"/>
	<xsl:template match="Item[@id='AR_empire_laurel_a']"/>
	<xsl:template match="Item[@id='AR_aserai_crown_a']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_a']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_b']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_c']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_d']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_e']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_f']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_g']"/>
	<xsl:template match="Item[@id='AR_aserai_archer_helmet_h']"/>
	<xsl:template match="Item[@id='AR_aserai_cataphract_helmet_a']"/>
	<xsl:template match="Item[@id='AR_aserai_cataphract_helmet_b']"/>
	<xsl:template match="Item[@id='AR_aserai_cataphract_helmet_c']"/>
	<xsl:template match="Item[@id='AR_aserai_cataphract_helmet_d']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_a']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_b']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_c']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_c2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_d']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_e']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_f']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_g']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_h']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_i']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_j']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_k']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_k2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_l']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_l2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_m']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_m2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_n']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_n2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_o']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_p']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_q']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_r']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_s']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_s2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_t']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_t2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_u']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_u2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_v']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_v2']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_w']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_x']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_y']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_z']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_za']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_zb']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_zc']"/>
	<xsl:template match="Item[@id='AR_aserai_helmet_zd']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_a']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_b']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_c']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_d']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_e']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_f']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_f2']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_g']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_g2']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_h']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_i']"/>
	<xsl:template match="Item[@id='AR_aserai_lord_helmet_j']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_a']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_a2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_b']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_b2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_c']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_d']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_f']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_f_decorated']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_g']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_h']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_i']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_j']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_k']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_l']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_m']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_n']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_o']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_p']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_q']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_r']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_s']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_t']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_u']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_v']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_v2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_w']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_w2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_x']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_x2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_y']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_y2']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_z']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_za']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_zb']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_zc']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_zd']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_ze']"/>
	<xsl:template match="Item[@id='AR_battania_helmet_zf']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_a']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_b']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_c']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_d']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_e']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_f']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_g']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_h']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_i']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_j']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_k']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_l']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_m']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_n']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_o']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_p']"/>
	<xsl:template match="Item[@id='AR_battania_lord_helmet_q']"/>
	<xsl:template match="Item[@id='AR_bone_helmet_a']"/>
	<xsl:template match="Item[@id='AR_bone_helmet_b']"/>
	<xsl:template match="Item[@id='AR_bone_helmet_c']"/>
	<xsl:template match="Item[@id='AR_closed_kettle_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_a2']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_b']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_b2']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_c']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_c2']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_d']"/>
	<xsl:template match="Item[@id='AR_empire_archer_helmet_d2']"/>
	<xsl:template match="Item[@id='ar_empire_cataphracts_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_crested_helm_a']"/>
	<xsl:template match="Item[@id='AR_empire_crested_helm_b']"/>
	<xsl:template match="Item[@id='AR_empire_desert_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_desert_helmet_b']"/>
	<xsl:template match="Item[@id='AR_empire_desert_helmet_c']"/>
	<xsl:template match="Item[@id='AR_empire_desert_helmet_d']"/>
	<xsl:template match="Item[@id='AR_empire_desert_helmet_e']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_b']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_c']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_d']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_e']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_f']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_g']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_h']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_i']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_j']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_k']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_l']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_m']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_n']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_o']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_o2']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_o3']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_p']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_q']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_r']"/>
	<xsl:template match="Item[@id='AR_empire_helmet_s']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_a']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_b']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_c']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_d']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_e']"/>
	<xsl:template match="Item[@id='AR_empire_legatus_helm_f']"/>
	<xsl:template match="Item[@id='AR_Empire_Lord_Guarded_Face_Helmet']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_a']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_b']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_c_a']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_d']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_e']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_f']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_g']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_h']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_i']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_j']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_k']"/>
	<xsl:template match="Item[@id='AR_empire_lord_helmet_l']"/>
	<xsl:template match="Item[@id='AR_Imperial_Archons_Helmet_a']"/>
	<xsl:template match="Item[@id='AR_Imperial_Archons_Helmet_b']"/>
	<xsl:template match="Item[@id='AR_Imperial_Crowned_Helmet_a']"/>
	<xsl:template match="Item[@id='AR_Imperial_Crowned_Helmet_b']"/>
	<xsl:template match="Item[@id='AR_intercisa_helmet_a']"/>
	<xsl:template match="Item[@id='AR_intercisa_helmet_b']"/>
	<xsl:template match="Item[@id='AR_intercisa_helmet_c']"/>
	<xsl:template match="Item[@id='AR_intercisa_helmet_d']"/>
	<xsl:template match="Item[@id='AR_intercisa_helmet_e']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_a']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_a_fur_a']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_a_fur_b']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_decorated']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_decorated_b']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_decorated_c']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_fur_a']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_fur_b']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_fur_c']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_plumed']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_b_plumed_b']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_cap']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_d_plumed_a']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_d_plumed_b']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_d_plumed_c']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_d_strips']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_d_strips_mail']"/>
	<xsl:template match="Item[@id='AR_roman_helmet_e_strips_mail']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_a']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_b']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_c']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_d']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_e']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_f']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_g']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_h']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_i']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_j']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_k']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_l']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_m']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_n']"/>
	<xsl:template match="Item[@id='AR_goth_helmet_o']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_a']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_b']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_b2']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_c']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_c_fur']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_c3']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_d']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_d2']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_e']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_f']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_g']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_h']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_i']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_j']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_k']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_l']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_m']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_n']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_o']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_p']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_q']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_r']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_s']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_t']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_u']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_v']"/>
	<xsl:template match="Item[@id='AR_khuzait_helmet_w']"/>
	<xsl:template match="Item[@id='AR_khuzait_hood_a']"/>
	<xsl:template match="Item[@id='AR_khuzait_hood_b']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_a']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_b']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_c']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_c2']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_d']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_d2']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_e']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_f']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_g']"/>
	<xsl:template match="Item[@id='AR_khuzait_lord_helmet_h']"/>
	<xsl:template match="Item[@id='AR_lion_head_c']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_a']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_a2']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_b']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_b2']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_c']"/>
	<xsl:template match="Item[@id='AR_phrygian_helmet_c2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_a']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_b']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_base']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_base_b']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_c']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_d']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_e']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_f']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_g']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_g2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_h']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_h2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_i']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_i2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_j']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_j2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_k']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_l']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_l2']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_m']"/>
	<xsl:template match="Item[@id='AR_sturgia_helmet_n']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_a']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_b']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_b2']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_c']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_d']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_e']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_f']"/>
	<xsl:template match="Item[@id='AR_vaegir_helmet_g']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_b']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_c']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_c2']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_d']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_e']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_f']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_g']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_h']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_i']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_j']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_k']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_l']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_m']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_n']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_o']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_p']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_q']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_q2']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_r']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_r2']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_s']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_t']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_u']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_u2']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_v']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_w']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_x']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_y']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_z']"/>
	<xsl:template match="Item[@id='AR_vlandia_helmet_z2']"/>
	<xsl:template match="Item[@id='AR_vlandia_lord_helmet_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_lord_helmet_b']"/>
	<xsl:template match="Item[@id='AR_vlandia_lord_helmet_c']"/>
	<xsl:template match="Item[@id='AR_vlandia_lord_helmet_d']"/>
	<xsl:template match="Item[@id='AR_vlandian_crown_mask_a']"/>
	<xsl:template match="Item[@id='AR_vlandian_crown_mask_b']"/>
	<xsl:template match="Item[@id='AR_vlandian_knights_helmet_a']"/>
	<xsl:template match="Item[@id='AR_vlandian_knights_helmet_b']"/>
	<xsl:template match="Item[@id='AR_vlandian_knights_helmet_c']"/>
	<xsl:template match="Item[@id='AR_vlandia_royal_helmet_a']"/>
	<xsl:template match="Item[@id='AR_vlandia_royal_helmet_b']"/>
	<!-- #endregion -->
	<!-- region OSA_bl_newequipment_items-->
	<xsl:template match="Item[@id='pauldron_cape_z']"/>
	<xsl:template match="Item[@id='lamellar_shoulder']"/>
	<xsl:template match="Item[@id='lamellar_shoulder_scarf']"/>
	<xsl:template match="Item[@id='brass_lamellar_cape']"/>
	<xsl:template match="Item[@id='brass_lamellar_cape_z']"/>
	<xsl:template match="Item[@id='crown_x']"/>
	<xsl:template match="Item[@id='crown_z']"/>
	<xsl:template match="Item[@id='tiara_x']"/>
	<xsl:template match="Item[@id='wolfhelmet']"/>
	<xsl:template match="Item[@id='battanian_crown']"/>
	<xsl:template match="Item[@id='bearhelmet']"/>
	<xsl:template match="Item[@id='roman_helmet_z']"/>
	<xsl:template match="Item[@id='visored_helmet_x']"/>
	<xsl:template match="Item[@id='kettle_helmet_sturgia']"/>
	<xsl:template match="Item[@id='visored_kettle_b']"/>
	<xsl:template match="Item[@id='visored_cap']"/>
	<xsl:template match="Item[@id='full_helm_over_mail_coif_x']"/>
	<xsl:template match="Item[@id='full_helm_over_mail_coif_z']"/>
	<!-- #endregion -->
</xsl:stylesheet>