<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<!-- Identity template to copy everything by default -->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_vlandia_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='vlandia_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='vlandia_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='vlandia_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='vla_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='vla_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='vla_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='vla_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='vla_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='vla_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='vla_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='vla_civ_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='vla_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='vla_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_vla_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_vla_cutscene_template']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_battania_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_battania']"/>
	<xsl:template match="EquipmentRoster[@id='battania_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='battania_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='battania_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='bat_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='bat_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='bat_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='bat_bat_template_wild']"/>
	<xsl:template match="EquipmentRoster[@id='bat_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='bat_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='bat_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='bat_civ_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='bat_civ_template_wild']"/>
	<xsl:template match="EquipmentRoster[@id='bat_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='bat_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='bat_noncom_template_wild']"/>
	<xsl:template match="EquipmentRoster[@id='bat_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_0_battania']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_bat_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_bat_cutscene_template']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_khuzait_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='khuzait_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='khuzait_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='khuzait_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='khu_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='khu_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='khu_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='khu_bat_template_nomad']"/>
	<xsl:template match="EquipmentRoster[@id='khu_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='khu_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='khu_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='khu_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='khu_civ_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='khu_civ_template_nomad']"/>
	<xsl:template match="EquipmentRoster[@id='khu_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='khu_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_khu_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_khu_cutscene_template']"/>
	<!--  -->
	<xsl:template match="EquipmentRoster[@id='npc_disguised_hero_equipment_template']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_empire_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_empire']"/>
	<xsl:template match="EquipmentRoster[@id='civillian_template_gangster_tier1_empire']"/>
	<xsl:template match="EquipmentRoster[@id='civillian_template_gangster_tier2_empire']"/>
	<xsl:template match="EquipmentRoster[@id='civillian_template_gangster_tier3_empire']"/>
	<xsl:template match="EquipmentRoster[@id='empire_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='empire_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='empire_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_empire']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_stoic']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_southfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_northfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='emp_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_stoic']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_southfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_northfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='emp_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='emp_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='emp_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='emp_noncom_template_stoic']"/>
	<xsl:template match="EquipmentRoster[@id='emp_noncom_template_southfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='emp_noncom_template_northfrontier']"/>
	<xsl:template match="EquipmentRoster[@id='conspirator_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_emp_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_emp_cutscene_template']"/>
	
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_sturgia_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='sturgia_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='sturgia_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='sturgia_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='stu_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='stu_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='stu_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='stu_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='stu_bat_template_woodsman']"/>
	<xsl:template match="EquipmentRoster[@id='stu_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='stu_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='stu_civ_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='stu_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='stu_civ_template_woodsman']"/>
	<xsl:template match="EquipmentRoster[@id='stu_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='stu_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='stu_noncom_template_woods']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_0_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_stu_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_stu_cutscene_template']"/>
	
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_aserai_civilian']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_template_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_armed_wanderer_equipment_template_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_companion_equipment_template_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='aserai_troop_civilian_template_t1']"/>
	<xsl:template match="EquipmentRoster[@id='aserai_troop_civilian_template_t2']"/>
	<xsl:template match="EquipmentRoster[@id='aserai_troop_civilian_template_t3']"/>
	<xsl:template match="EquipmentRoster[@id='ase_bat_template_medium']"/>
	<xsl:template match="EquipmentRoster[@id='ase_bat_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='ase_bat_template_heavy']"/>
	<xsl:template match="EquipmentRoster[@id='ase_bat_template_bedouin']"/>
	<xsl:template match="EquipmentRoster[@id='ase_bat_template_lady']"/>
	<xsl:template match="EquipmentRoster[@id='ase_civ_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='ase_civ_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='ase_civ_template_lady_normal']"/>
	<xsl:template match="EquipmentRoster[@id='ase_civ_template_bedouin']"/>
	<xsl:template match="EquipmentRoster[@id='ase_noncom_template_flamboyant']"/>
	<xsl:template match="EquipmentRoster[@id='ase_noncom_template_default']"/>
	<xsl:template match="EquipmentRoster[@id='ase_noncom_template_bedouin']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_0_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='marriage_female_ase_cutscene_template']"/>
	<xsl:template match="EquipmentRoster[@id='comingofage_kid_ase_cutscene_template']"/>
	
</xsl:stylesheet>
