<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- region OSA_ar_reforms_saddlery-->
	<xsl:template match="Item[@id='AR_horse_armor_a']"/>
	<xsl:template match="Item[@id='AR_horse_armor_a2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_b']"/>
	<xsl:template match="Item[@id='AR_horse_armor_b2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_c']"/>
	<xsl:template match="Item[@id='AR_horse_armor_c2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_c3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_d']"/>
	<xsl:template match="Item[@id='AR_horse_armor_d2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_d3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_e']"/>
	<xsl:template match="Item[@id='AR_horse_armor_f']"/>
	<xsl:template match="Item[@id='AR_horse_armor_g']"/>
	<xsl:template match="Item[@id='AR_horse_armor_h']"/>
	<xsl:template match="Item[@id='AR_horse_armor_i']"/>
	<xsl:template match="Item[@id='AR_horse_armor_j']"/>
	<xsl:template match="Item[@id='AR_horse_armor_j2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_k']"/>
	<xsl:template match="Item[@id='AR_horse_armor_k2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_l']"/>
	<xsl:template match="Item[@id='AR_horse_armor_m']"/>
	<xsl:template match="Item[@id='AR_horse_armor_n']"/>
	<xsl:template match="Item[@id='AR_horse_armor_n2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_n3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_o']"/>
	<xsl:template match="Item[@id='AR_horse_armor_p']"/>
	<xsl:template match="Item[@id='AR_horse_armor_p2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_q']"/>
	<xsl:template match="Item[@id='AR_horse_armor_q2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_q3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_r']"/>
	<xsl:template match="Item[@id='AR_horse_armor_r2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_r3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_s']"/>
	<xsl:template match="Item[@id='AR_horse_armor_t']"/>
	<xsl:template match="Item[@id='AR_horse_armor_t2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_u']"/>
	<xsl:template match="Item[@id='AR_horse_armor_u2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_v']"/>
	<xsl:template match="Item[@id='AR_horse_armor_w']"/>
	<xsl:template match="Item[@id='AR_horse_armor_x']"/>
	<xsl:template match="Item[@id='AR_horse_armor_y']"/>
	<xsl:template match="Item[@id='AR_horse_armor_y2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_y3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_z']"/>
	<xsl:template match="Item[@id='AR_horse_armor_z2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_z3']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zaa']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zab']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zac']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zad']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zae']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zae2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zaf']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zag']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zah']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zai']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zaj']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zak']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zal']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zam']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zan']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zao']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zap']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zap2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zaq']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zaq2']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zar']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zas']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zat']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zau']"/>
	<xsl:template match="Item[@id='AR_horse_armor_za']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zb']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zc']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zd']"/>
	<xsl:template match="Item[@id='AR_horse_armor_ze']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zf']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zg']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zh']"/>
	<xsl:template match="Item[@id='AR_horse_armor_zi']"/>
	<!-- #endregion -->
	<!-- region OSA_dz_custom_saddlery-->
	<xsl:template match="Item[@id='DZ_horse_armor_a']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_b']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_c']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_d']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_e']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_f']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_g']"/>
	<xsl:template match="Item[@id='DZ_horse_armor_h']"/>
	<!-- #endregion -->
	<!-- region OSA_tv_custom_saddlery-->
	<xsl:template match="Item[@id='tv_camel_armor_a']"/>
	<xsl:template match="Item[@id='tv_camel_armor_b']"/>
	<xsl:template match="Item[@id='tv_camel_armor_c']"/>
	<xsl:template match="Item[@id='tv_camel_armor_d']"/>
	<xsl:template match="Item[@id='tv_camel_armor_e']"/>
	<xsl:template match="Item[@id='tv_camel_armor_f']"/>
	<xsl:template match="Item[@id='tv_camel_armor_g']"/>
	<xsl:template match="Item[@id='tv_camel_armor_h']"/>
	<xsl:template match="Item[@id='tv_camel_armor_i']"/>
	<xsl:template match="Item[@id='tv_camel_armor_j']"/>
	<xsl:template match="Item[@id='TV_horse_armor_a']"/>
	<xsl:template match="Item[@id='TV_horse_armor_a2']"/>
	<xsl:template match="Item[@id='TV_horse_armor_a3']"/>
	<xsl:template match="Item[@id='TV_horse_armor_b']"/>
	<xsl:template match="Item[@id='TV_horse_armor_b2']"/>
	<xsl:template match="Item[@id='TV_horse_armor_b3']"/>
	<xsl:template match="Item[@id='TV_horse_armor_c']"/>
	<xsl:template match="Item[@id='TV_horse_armor_c2']"/>
	<xsl:template match="Item[@id='TV_horse_armor_c3']"/>
	<xsl:template match="Item[@id='TV_horse_armor_d']"/>
	<xsl:template match="Item[@id='TV_horse_armor_d2']"/>
	<xsl:template match="Item[@id='TV_horse_armor_d3']"/>
	<!-- #endregion -->
</xsl:stylesheet>