<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="Item[@id='levy_hood_1']"/>
	<xsl:template match="Item[@id='steelcross1']"/>
	<xsl:template match="Item[@id='el_cloak_1']"/>
	<xsl:template match="Item[@id='el_Cross_cloak_1']"/>
	<xsl:template match="Item[@id='eyepatch_1']"/>
	<xsl:template match="Item[@id='cape_1']"/>
	<xsl:template match="Item[@id='royal_necklace_c1']"/>
	<xsl:template match="Item[@id='shoulder_cloth1']"/>
	<xsl:template match="Item[@id='leathergloves_1']"/>
	<xsl:template match="Item[@id='bl_plategloves_1']"/>
	<xsl:template match="Item[@id='hourglasss_1n']"/>
	<xsl:template match="Item[@id='gl_plategloves_1']"/>
	<xsl:template match="Item[@id='plated_gloves_1']"/>
	<xsl:template match="Item[@id='hourglasss_1']"/>
	<xsl:template match="Item[@id='mailgloves_1']"/>
	<xsl:template match="Item[@id='pikinier_pot1']"/>
	<xsl:template match="Item[@id='morion1_proto']"/>
	<xsl:template match="Item[@id='lobsterhelm1']"/>
	<xsl:template match="Item[@id='landsknechthat_1']"/>
	<xsl:template match="Item[@id='whussar_helmet_1']"/>
	<xsl:template match="Item[@id='renarmet_1']"/>
	<xsl:template match="Item[@id='renclos_burgonet1']"/>
	<xsl:template match="Item[@id='goldengraved_burgonet1']"/>
	<xsl:template match="Item[@id='ren_breastplate_1']"/>
	<xsl:template match="Item[@id='pikinier_bando_coat_1']"/>
	<xsl:template match="Item[@id='pikkaner_armor_1']"/>
	<xsl:template match="Item[@id='ren_armor_cloth1']"/>
	<xsl:template match="Item[@id='ren_fullplate_1']"/>
	<xsl:template match="Item[@id='ren_blackarmor1_1']"/>
	<xsl:template match="Item[@id='WHussar_armor_1']"/>
	<xsl:template match="Item[@id='hempcovered_boots_1']"/>
	<xsl:template match="Item[@id='bootssta_1']"/>
	<xsl:template match="Item[@id='chaperone1']"/>
	<xsl:template match="Item[@id='german_sallet_1']"/>
	<xsl:template match="Item[@id='open_sallet_1']"/>
	<xsl:template match="Item[@id='italian_sallet_1']"/>
	<xsl:template match="Item[@id='piecesallet_1']"/>
	<xsl:template match="Item[@id='sta_sallet_1p']"/>
	<xsl:template match="Item[@id='sta_sallet_1']"/>
	<xsl:template match="Item[@id='ital_bascinet_1p']"/>
	<xsl:template match="Item[@id='ital_bascinet_1']"/>
	<xsl:template match="Item[@id='wide_sallet_1']"/>
	<xsl:template match="Item[@id='velvet_sallet_gold_1']"/>
	<xsl:template match="Item[@id='noblewrapperarmet_1']"/>
	<xsl:template match="Item[@id='bellows_1']"/>
	<xsl:template match="Item[@id='openosallet_1']"/>
	<xsl:template match="Item[@id='burgundkettle1']"/>
	<xsl:template match="Item[@id='burgundkettle1p']"/>
	<xsl:template match="Item[@id='late_germ_kettle1']"/>
	<xsl:template match="Item[@id='late_munsallet_p1']"/>
	<xsl:template match="Item[@id='15th_germ_gret_basc1']"/>
	<xsl:template match="Item[@id='decor_grt_bsc_1']"/>
	<xsl:template match="Item[@id='greatbascinet1']"/>
	<xsl:template match="Item[@id='nasalbarbutep_1']"/>
	<xsl:template match="Item[@id='opensallet_1_late']"/>
	<xsl:template match="Item[@id='barbuta_1']"/>
	<xsl:template match="Item[@id='sta_armetp']"/>
	<xsl:template match="Item[@id='sta_armet']"/>
	<xsl:template match="Item[@id='blacksallet_1']"/>
	<xsl:template match="Item[@id='pan_sallet1']"/>
	<xsl:template match="Item[@id='decorated_sallet_gld']"/>
	<xsl:template match="Item[@id='mun_sallet_mailcoif_1']"/>
	<xsl:template match="Item[@id='sta_barbute_1']"/>
	<xsl:template match="Item[@id='p_osallet_1']"/>
	<xsl:template match="Item[@id='p_osallet_1p']"/>
	<xsl:template match="Item[@id='salada_1']"/>
	<xsl:template match="Item[@id='sallet_faceplate_1']"/>
	<xsl:template match="Item[@id='heavybevor_late1']"/>
	<xsl:template match="Item[@id='noble_bevor_1']"/>
	<xsl:template match="Item[@id='breastplate_shash1']"/>
	<xsl:template match="Item[@id='late_brig_armor1']"/>
	<xsl:template match="Item[@id='15th_duplet_brig_1']"/>
	<xsl:template match="Item[@id='late_hlafpalte_brig_duplet1']"/>
	<xsl:template match="Item[@id='fluted_heavy_armor_1']"/>
	<xsl:template match="Item[@id='gothi_plate1']"/>
	<xsl:template match="Item[@id='15th_heavypalte_2']"/>
	<xsl:template match="Item[@id='15th_heavypalte_1']"/>
	<xsl:template match="Item[@id='el_15th_heavyarmor1']"/>
	<xsl:template match="Item[@id='15th_el_platearmor2']"/>
	<xsl:template match="Item[@id='15th_el_platearmor1']"/>
	<xsl:template match="Item[@id='strapped_brigandine_1']"/>
	<xsl:template match="Item[@id='halfplate_gambeson_jackchains_1']"/>
	<xsl:template match="Item[@id='breastplate_gambeson_1']"/>
	<xsl:template match="Item[@id='heavytabard_tableau_1']"/>
	<xsl:template match="Item[@id='15th_tabard_armor_1']"/>
	<xsl:template match="Item[@id='tab_sleeved_tabard_1']"/>
	<xsl:template match="Item[@id='giornea_tableau1']"/>
	<xsl:template match="Item[@id='el15_tabard_tableau1']"/>
	<xsl:template match="Item[@id='tableau_tabard_breastplatecloth1']"/>
	<xsl:template match="Item[@id='sta_platelegs_1gold']"/>
	<xsl:template match="Item[@id='sta_platelegs_1']"/>
	<xsl:template match="Item[@id='longboots_1']"/>
	<xsl:template match="Item[@id='late_mun_hosen_1']"/>
	<xsl:template match="Item[@id='plated_hosen_1']"/>
	<xsl:template match="Item[@id='poleyn_hosen_1']"/>
	<xsl:template match="Item[@id='greathelmet_cloth_1']"/>
	<xsl:template match="Item[@id='houndskull_ba_1']"/>
	<xsl:template match="Item[@id='spoledo_bascinet_1']"/>
	<xsl:template match="Item[@id='venetian_bascinet1']"/>
	<xsl:template match="Item[@id='14th_noble_greathelmet1']"/>
	<xsl:template match="Item[@id='bascinetorle_1']"/>
	<xsl:template match="Item[@id='goldstud_bascinet1']"/>
	<xsl:template match="Item[@id='14th_goldrim_visbascinet1']"/>
	<xsl:template match="Item[@id='14th_goldrim_visbascinet2']"/>
	<xsl:template match="Item[@id='14th_painted_bascinet1']"/>
	<xsl:template match="Item[@id='klappvisor1']"/>
	<xsl:template match="Item[@id='high_visored_bascinet1c']"/>
	<xsl:template match="Item[@id='high_visored_bascinet1']"/>
	<xsl:template match="Item[@id='bretache1']"/>
	<xsl:template match="Item[@id='chap_kettle1']"/>
	<xsl:template match="Item[@id='bascinet_worn']"/>
	<xsl:template match="Item[@id='bretache_n1']"/>
	<xsl:template match="Item[@id='munition_bascinet1']"/>
	<xsl:template match="Item[@id='flutkettle_1']"/>
	<xsl:template match="Item[@id='flatkettle_1']"/>
	<xsl:template match="Item[@id='gld_grff_basc1']"/>
	<xsl:template match="Item[@id='pig_klappvisor_1']"/>
	<xsl:template match="Item[@id='bascinet_withvisor_1']"/>
	<xsl:template match="Item[@id='bascineto1']"/>
	<xsl:template match="Item[@id='houndskull_brass_1']"/>
	<xsl:template match="Item[@id='scalecervelliere1']"/>
	<xsl:template match="Item[@id='bl_winged_helmet1']"/>
	<xsl:template match="Item[@id='midtableau_corrazina_1']"/>
	<xsl:template match="Item[@id='14_tabardtableau_plate']"/>
	<xsl:template match="Item[@id='joupon_1']"/>
	<xsl:template match="Item[@id='plated_joupon1']"/>
	<xsl:template match="Item[@id='mun_gambeson_breastplate_1']"/>
	<xsl:template match="Item[@id='el_cop_1']"/>
	<xsl:template match="Item[@id='14th_splinted_midplate_1']"/>
	<xsl:template match="Item[@id='14th_bl_decorplate_1']"/>
	<xsl:template match="Item[@id='light_tunic_mailed_1']"/>
	<xsl:template match="Item[@id='14th_decorplate1']"/>
	<xsl:template match="Item[@id='14th_transi_armor_1']"/>
	<xsl:template match="Item[@id='churburg_1']"/>
	<xsl:template match="Item[@id='14th_paint_midplate_1']"/>
	<xsl:template match="Item[@id='tabarded_14th_noble_1']"/>
	<xsl:template match="Item[@id='tabarded_14th_noble_2']"/>
	<xsl:template match="Item[@id='14th_tabarded_platearmor_1']"/>
	<xsl:template match="Item[@id='14th_platearmor_1']"/>
	<xsl:template match="Item[@id='14th_platearmor_2']"/>
	<xsl:template match="Item[@id='14th_corrazzina_reinf_1']"/>
	<xsl:template match="Item[@id='corrazina_1']"/>
	<xsl:template match="Item[@id='high_padding_armoured_1']"/>
	<xsl:template match="Item[@id='reinfoced_14th_breastplate_1']"/>
	<xsl:template match="Item[@id='tab_vest_mailsleeves_1']"/>
	<xsl:template match="Item[@id='levy_cop_gamb_1']"/>
	<xsl:template match="Item[@id='tabard_under_breastplate_1']"/>
	<xsl:template match="Item[@id='14th_el_tabard_tab']"/>
	<xsl:template match="Item[@id='bl_platelegs_1']"/>
	<xsl:template match="Item[@id='14_midsplinted_greaves']"/>
	<xsl:template match="Item[@id='14_noblesabaton1']"/>
	<xsl:template match="Item[@id='high_splinted_leggings1']"/>
	<xsl:template match="Item[@id='14_decor_paltedboots_noble1']"/>
	<xsl:template match="Item[@id='sugarloaf_1']"/>
	<xsl:template match="Item[@id='sugarloaf_2']"/>
	<xsl:template match="Item[@id='horned_grthelmet_1']"/>
	<xsl:template match="Item[@id='maciejowski_helmet']"/>
	<xsl:template match="Item[@id='p_grethelmet_1']"/>
	<xsl:template match="Item[@id='grhelmet_cross1']"/>
	<xsl:template match="Item[@id='el_brass_greathelmet1']"/>
	<xsl:template match="Item[@id='greathelmet_sta']"/>
	<xsl:template match="Item[@id='orle_kettle1']"/>
	<xsl:template match="Item[@id='bucketkettle_1']"/>
	<xsl:template match="Item[@id='strapped_kettle_1']"/>
	<xsl:template match="Item[@id='sta_kettle_p']"/>
	<xsl:template match="Item[@id='coat_plate_1']"/>
	<xsl:template match="Item[@id='tab_coatplate_1']"/>
	<xsl:template match="Item[@id='el_surcoat_tab1']"/>
	<xsl:template match="Item[@id='surcoat_tableau_1']"/>
	<xsl:template match="Item[@id='surcoat_tableau_1o']"/>
	<xsl:template match="Item[@id='norm_enclosed_helmet1']"/>
	<xsl:template match="Item[@id='nob_norm_facepalte_1']"/>
	<xsl:template match="Item[@id='p_iber_faceplate_1']"/>
	<xsl:template match="Item[@id='norm_nasal_p_1']"/>
	<xsl:template match="Item[@id='12th_el_nasal_1']"/>
	<xsl:template match="Item[@id='sta_italonorman_1']"/>
	<xsl:template match="Item[@id='el_enclosed_helmet_1']"/>
	<xsl:template match="Item[@id='fr_el_flatkettle1']"/>
	<xsl:template match="Item[@id='e_lkettle_1']"/>
	<xsl:template match="Item[@id='el_scandinasal1']"/>
	<xsl:template match="Item[@id='sta_norm_nasal_1']"/>
	<xsl:template match="Item[@id='p_segm_nasal_1']"/>
	<xsl:template match="Item[@id='decorated_el_nasal_1']"/>
	<xsl:template match="Item[@id='wolfram_1']"/>
	<xsl:template match="Item[@id='t_shaped_1']"/>
	<xsl:template match="Item[@id='reinf_nasal_1']"/>
	<xsl:template match="Item[@id='protofaceplate_1']"/>
	<xsl:template match="Item[@id='painted_es_naal1']"/>
	<xsl:template match="Item[@id='p_es_faceplate_1']"/>
	<xsl:template match="Item[@id='norm_potplate_1']"/>
	<xsl:template match="Item[@id='nasal_conical_flattop1']"/>
	<xsl:template match="Item[@id='levy_nasal_el_1']"/>
	<xsl:template match="Item[@id='lether_cercelliere_1']"/>
	<xsl:template match="Item[@id='heil_faceplate_1']"/>
	<xsl:template match="Item[@id='es_nasl_flattop']"/>
	<xsl:template match="Item[@id='es_ib_faceplate_1']"/>
	<xsl:template match="Item[@id='es_flattop_1']"/>
	<xsl:template match="Item[@id='es_faceplate_1']"/>
	<xsl:template match="Item[@id='es_el_enclosed_helmet_1']"/>
	<xsl:template match="Item[@id='englonged_nasal_1']"/>
	<xsl:template match="Item[@id='decor_nasal_2_1']"/>
	<xsl:template match="Item[@id='decor_nasal_1']"/>
	<xsl:template match="Item[@id='decor_facepalte_1']"/>
	<xsl:template match="Item[@id='cross_faceplate_1']"/>
	<xsl:template match="Item[@id='conical_flattop1']"/>
	<xsl:template match="Item[@id='cercelliere_1']"/>
	<xsl:template match="Item[@id='br_nasal_1']"/>
	<xsl:template match="Item[@id='segmentednasal_elcoif']"/>
	<xsl:template match="Item[@id='anachrism_facepalte_1']"/>
	<xsl:template match="Item[@id='baltic_slonim1']"/>
	<xsl:template match="Item[@id='early_decor_helmet1']"/>
	<xsl:template match="Item[@id='andalus_helmet1']"/>
	<xsl:template match="Item[@id='andalus_phelmet1']"/>
	<xsl:template match="Item[@id='knasal_1']"/>
	<xsl:template match="Item[@id='pnasalflat_1']"/>
	<xsl:template match="Item[@id='el_phrygnasal1']"/>
	<xsl:template match="Item[@id='flattopnasal_noble1']"/>
	<xsl:template match="Item[@id='gld_itaonorman_1']"/>
	<xsl:template match="Item[@id='cervelliere_padding_hood1']"/>
	<xsl:template match="Item[@id='p_norm_facepalte_1']"/>
	<xsl:template match="Item[@id='phrygian_nasal_p1']"/>
	<xsl:template match="Item[@id='el_brass_topnasal1']"/>
	<xsl:template match="Item[@id='el_painted_topnasal1']"/>
	<xsl:template match="Item[@id='el_hevy_faceplate1']"/>
	<xsl:template match="Item[@id='el_hevy_faceplate1n']"/>
	<xsl:template match="Item[@id='norm_hauberk_sleeves_1']"/>
	<xsl:template match="Item[@id='norm_sleeved_hauberk_1']"/>
	<xsl:template match="Item[@id='el_hauberk_1']"/>
	<xsl:template match="Item[@id='norm_hauberk_1']"/>
	<xsl:template match="Item[@id='chain_hauberk_1']"/>
	<xsl:template match="Item[@id='sta_nasal_el1']"/>
	<xsl:template match="Item[@id='sta_nasal_elwool']"/>
	<xsl:template match="Item[@id='levied_flattop_wool']"/>
	<xsl:template match="Item[@id='wencheslav_nasal1']"/>
	<xsl:template match="Item[@id='poor_el_boots1']"/>
	<xsl:template match="Item[@id='strapped_hosen_1']"/>
	<xsl:template match="Item[@id='mailchasseus_1']"/>
	<xsl:template match="Item[@id='arm_coif1']"/>
	<xsl:template match="Item[@id='fullmailcoif1']"/>
	<xsl:template match="Item[@id='early_mailcoif_1']"/>
	<xsl:template match="Item[@id='chainmail_tableau_1']"/>
	<xsl:template match="Item[@id='chainmail_ailette_1']"/>
	<xsl:template match="Item[@id='quartered_tabard_1']"/>
	<xsl:template match="Item[@id='tab_gamb_2']"/>
	<xsl:template match="Item[@id='tab_tunic1']"/>
	<xsl:template match="Item[@id='tab_gambeson_1']"/>
	<xsl:template match="Item[@id='padded_surcoat_1']"/>
	<xsl:template match="Item[@id='wool_tunic1']"/>
	<xsl:template match="Item[@id='levy_gambeson_1']"/>
	<xsl:template match="Item[@id='esmail_tunic1']"/>
	<xsl:template match="Item[@id='surcoat_1']"/>
	<xsl:template match="Item[@id='surcoat_2']"/>
	<xsl:template match="Item[@id='surcoat_3']"/>
	<xsl:template match="Item[@id='surcoat_4']"/>
	<xsl:template match="Item[@id='surcoat_5']"/>
	<xsl:template match="Item[@id='surcoat_6']"/>
	<xsl:template match="Item[@id='scale_tunic_1']"/>
	<xsl:template match="Item[@id='mail_vest_1']"/>
	<xsl:template match="Item[@id='vest_sleeved_mail_1']"/>
	<xsl:template match="Item[@id='gamb_tunic_1']"/>
	<xsl:template match="Item[@id='unigambeson_sleeves_1']"/>
	<xsl:template match="Item[@id='gambeson_levy1']"/>
	<xsl:template match="Item[@id='uni_gambeson_1']"/>
	<xsl:template match="Item[@id='chainskirt_strap_1']"/>
	<xsl:template match="Item[@id='valsgarde_1']"/>
	<xsl:template match="Item[@id='saxonhelmet_1']"/>
	<xsl:template match="Item[@id='byz_decor_kettle1']"/>
	<xsl:template match="Item[@id='varang_helmet1']"/>
	<xsl:template match="Item[@id='laced_nasal_fm']"/>
	<xsl:template match="Item[@id='byz_noblekettle_1']"/>
	<xsl:template match="Item[@id='byz_nasal_1']"/>
	<xsl:template match="Item[@id='byz_mail_1']"/>
	<xsl:template match="Item[@id='byz_noble_armor1']"/>
	<xsl:template match="Item[@id='byz_lam_1']"/>
	<xsl:template match="Item[@id='noble_as_helmet1']"/>
	<xsl:template match="Item[@id='scarf_nasal_1']"/>
	<xsl:template match="Item[@id='seljuk_helmet_1']"/>
	<xsl:template match="Item[@id='khazangand_1']"/>
	<xsl:template match="Item[@id='early_norm_crown_1']"/>
	<xsl:template match="Item[@id='hre_emperor_nasal1']"/>
	<xsl:template match="Item[@id='caparison_template_anhalt']"/>
	<xsl:template match="Item[@id='caparison_template_anjou']"/>
	<xsl:template match="Item[@id='caparison_template_barbancon']"/>
	<xsl:template match="Item[@id='caparison_template_bavaria']"/>
	<xsl:template match="Item[@id='caparison_template_castilleandleon']"/>
	<xsl:template match="Item[@id='caparison_template_flandres']"/>
	<xsl:template match="Item[@id='caparison_template_gascony']"/>
	<xsl:template match="Item[@id='caparison_template_jerusalem']"/>
	<xsl:template match="Item[@id='caparison_template_lusignan_poitiers']"/>
	<xsl:template match="Item[@id='caparison_template_scotland']"/>
	<xsl:template match="Item[@id='caparison_template_sicily']"/>
	<xsl:template match="Item[@id='caparison_template_sweden']"/>
	<xsl:template match="Item[@id='caparison_template_teutonic2']"/>
	<xsl:template match="Item[@id='caparison_template_lionheart']"/>
	<xsl:template match="Item[@id='caparison_template_brabant']"/>
	<xsl:template match="Item[@id='caparison_template_brienne']"/>
	<xsl:template match="Item[@id='caparison_template_brittany']"/>
	<xsl:template match="Item[@id='caparison_template_champagne']"/>
	<xsl:template match="Item[@id='caparison_template_teutonic']"/>
	<xsl:template match="Item[@id='caparison_template_lancaster']"/>
	<xsl:template match="Item[@id='caparison_1']"/>
	<xsl:template match="Item[@id='whussar_horsearmor_1']"/>
	<xsl:template match="Item[@id='teardrop_shield_1']"/>
</xsl:stylesheet>