<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- region OSA_ar_reforms_shields-->
	<xsl:template match="Item[@id='AR_shield_infantry_a']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_a2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_b']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_b2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_c']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_c2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_d']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_d2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_e']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_e2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_f']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_f2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_g']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_g2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_h']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_h2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_i']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_j']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_k']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_l']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_m']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_m2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_n']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_n2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_o']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_o2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_p']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_q']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_r']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_r2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_s']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_s2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_t']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_t2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_u']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_u2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_v']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_w']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_x']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_y']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_z']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_za']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zb']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zc']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zd']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_ze']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zf']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zg']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zh']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zi']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zj']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zk']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zl']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zm']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zm2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zn']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zn2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zo']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zo2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zp']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zq']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zr']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zs']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zt']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zu']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zv']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zw']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zx']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zy']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zz']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zza']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzb']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzb2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzc']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzc2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzd']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzd2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zze']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zze2']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzf']"/>
	<xsl:template match="Item[@id='AR_shield_infantry_zzg']"/>
	<!-- #endregion -->
	<!-- region OSA_ar_reforms_slings-->
	<xsl:template match="Item[@id='AR_sling_a']"/>
	<xsl:template match="Item[@id='AR_sling_b']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_a']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_a1']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_a2']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b1']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b2']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b3']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b4']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_b5']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_c']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_c1']"/>
	<xsl:template match="Item[@id='AR_sling_bullets_d']"/>
	<!-- #endregion -->
	<!-- region OSA_ar_reforms_weapons-->
	<xsl:template match="Item[@id='AR_plumbata']"/>
	<xsl:template match="Item[@id='AR_plumbata_heavy']"/>
	<xsl:template match="Item[@id='AR_martiobarbuli']"/>
	<xsl:template match="Item[@id='AR_throwing_pot']"/>
	<xsl:template match="Item[@id='AR_war_dart_a']"/>
	<xsl:template match="Item[@id='AR_war_dart_b']"/>
	<xsl:template match="Item[@id='AR_naptha_pot']"/>
	<xsl:template match="Item[@id='AR_cheirosiphon_a']"/>
	<xsl:template match="Item[@id='AR_cheirosiphon_ammo_a']"/>
	<xsl:template match="CraftedItem[@id='AR_seax_a']"/>
	<xsl:template match="CraftedItem[@id='AR_aserai_axe_1_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_axe_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_axe_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_axe_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_axe_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_imperial_axe_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_imperial_axe_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_imperial_axe_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_iltanlar_axe_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_iltanlar_axe_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_iltanlar_axe_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_iltanlar_axe_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_vlandia_axe_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_2haxe_3_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_2haxe_4_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_vlandia_2haxe_3_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_vlandia_2haxe_4_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_vlandia_2haxe_2_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_aserai_noble_sword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_aserai_royal_sword_1_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_aserai_royal_sword_2_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_sword_1_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_sword_4_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_sword_5_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_sword_5_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_sword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_noble_sword_4_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_noble_sword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_noble_sword_6_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_royal_sword_1_t6']"/>
	<xsl:template match="CraftedItem[@id='AR_khuzait_noble_sword_4_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_khuzait_noble_sword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_shotel_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_shotel_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_shotel_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_sickle_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_sickle_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_vlandia_noble_sword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_2hsword_4_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_2hsword_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_2hsword_6_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_war_razor_2hsword_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_war_razor_2hsword_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_pugio_a']"/>
	<xsl:template match="CraftedItem[@id='AR_seax_b']"/>
	<xsl:template match="CraftedItem[@id='AR_seax_c']"/>
	<xsl:template match="CraftedItem[@id='AR_khanjar_a']"/>
	<xsl:template match="CraftedItem[@id='AR_kituga_a']"/>
	<xsl:template match="CraftedItem[@id='AR_skaen_a']"/>
	<xsl:template match="CraftedItem[@id='AR_empire_mace_1_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_1_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_3_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_4_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_5_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_5_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_mace_6_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_khuzait_mace_2_t3']"/>
	<xsl:template match="CraftedItem[@id='AR_battania_mace_3_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_2h_mace_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_2h_mace_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_noble_2h_mace_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_noble_2h_mace_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_darshi_royal_2h_mace_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_peasant_maul_t1_1']"/>
	<xsl:template match="CraftedItem[@id='AR_northern_2h_mace_t4']"/>
	<xsl:template match="CraftedItem[@id='AR_northern_2h_mace_t5']"/>
	<xsl:template match="CraftedItem[@id='AR_crude_2h_mace_t2']"/>
	<xsl:template match="CraftedItem[@id='AR_crude_2h_mace_t3']"/>
	<!-- #endregion -->
	<!-- region OSA_crafting_pieces-->
	<xsl:template match="CraftingPiece[@id='spear_guard_9']"/>
	<xsl:template match="CraftingPiece[@id='AR_aserai_blade_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_aserai_blade_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_guard_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_guard_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_guard_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_guard_d']"/>
	<xsl:template match="CraftingPiece[@id='AR_basic_guard_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_basic_guard_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_sturgia_guard_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_pommel_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_pommel_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_pommel_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_battania_pommel_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_battania_pommel_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_basic_pommel_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_khuzait_pommel_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_mace_head_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_empire_mace_head_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_handle_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_handle_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_head_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_head_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_head_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_darshi_mace_head_d']"/>
	<xsl:template match="CraftingPiece[@id='AR_khuzait_mace_head_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_mace_head_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_blade_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_blade_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_blade_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_blade_d']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_blade_e']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_handle_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_handle_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_pommel_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_pommel_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_pommel_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_spear_guard_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_billhook_blade_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_SI_spear_handle_a']"/>
	<xsl:template match="CraftingPiece[@id='AR_SI_spear_handle_b']"/>
	<xsl:template match="CraftingPiece[@id='AR_SI_spear_handle_c']"/>
	<xsl:template match="CraftingPiece[@id='AR_SI_spear_handle_d']"/>
	<xsl:template match="CraftingPiece[@id='AR_SI_spear_handle_e']"/>
	<!-- #endregion -->
	<!-- region OSA_extra_contribution_weapons-->
	<xsl:template match="Item[@id='AD_shield_infantry_a']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_a2']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_b']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_b2']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_c']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_c2']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_d']"/>
	<xsl:template match="Item[@id='AD_shield_infantry_d2']"/>
	<!-- #endregion -->
</xsl:stylesheet>