<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="Item[@id='coat_of_plates1_c']"/>
	<xsl:template match="Item[@id='coat_of_plates2_c']"/>
	<xsl:template match="Item[@id='coat_of_plates3_c']"/>
	<xsl:template match="Item[@id='coat_of_plates4_c']"/>
	<xsl:template match="Item[@id='coat_of_plates5_c']"/>
	<xsl:template match="Item[@id='swadian_brass_plate_armor']"/>
	<xsl:template match="Item[@id='swadian_leather_plate_armor']"/>
	<xsl:template match="Item[@id='swadian_plate_armor']"/>
	<xsl:template match="Item[@id='swadian_striped_plate_armor']"/>
	<xsl:template match="Item[@id='swadian_plate_with_armguards']"/>
	<xsl:template match="Item[@id='swadian_leather_plate_with_armguards']"/>
	<xsl:template match="Item[@id='swadian_striped_cuirass']"/>
	<xsl:template match="Item[@id='swadian_cuirass']"/>
	<xsl:template match="Item[@id='engraved_swadian_shoulders']"/>
	<xsl:template match="Item[@id='swadian_shoulders']"/>
	<xsl:template match="Item[@id='great_helm_base']"/>
	<xsl:template match="Item[@id='winged_great_helm_base']"/>
	<xsl:template match="Item[@id='great_helm_brass']"/>
	<xsl:template match="Item[@id='winged_great_helm_brass']"/>
	<xsl:template match="Item[@id='great_helm_dark']"/>
	<xsl:template match="Item[@id='winged_great_helm_dark']"/>
	<xsl:template match="Item[@id='royal_great_helm']"/>
	<xsl:template match="Item[@id='royal_great_helm_brass']"/>
	<xsl:template match="Item[@id='sallet_base']"/>
	<xsl:template match="Item[@id='sallet_crowned']"/>
	<xsl:template match="Item[@id='sallet_wings']"/>
	<xsl:template match="Item[@id='sallet_no_visor']"/>
	<xsl:template match="Item[@id='pigface_bascinet']"/>
	<xsl:template match="Item[@id='pigface_bascinet_feather']"/>
	<xsl:template match="Item[@id='pigface_bascinet_tail']"/>
	<xsl:template match="Item[@id='vlandian_helm_with_faceplate']"/>
	<xsl:template match="Item[@id='vlandian_helm_with_faceplate_blackend_brass']"/>
	<xsl:template match="Item[@id='vlandian_helm_with_faceplate_brass']"/>
	<xsl:template match="Item[@id='vlandian_helm_with_faceplate_painted']"/>
	<xsl:template match="Item[@id='italio_norman_helm_crown']"/>
	<xsl:template match="Item[@id='italio_norman_helm_bronze']"/>
	<xsl:template match="Item[@id='italio_norman_helm']"/>
	<xsl:template match="Item[@id='crowned_helm_with_brass_faceplate']"/>
	<xsl:template match="Item[@id='crowned_helm_with_faceplate']"/>
	<xsl:template match="Item[@id='fluted_helm_with_brass_faceplate']"/>
	<xsl:template match="Item[@id='fluted_helm_with_faceplate']"/>
	<xsl:template match="Item[@id='vlandian_helm_with_visor']"/>
	<xsl:template match="Item[@id='engraved_vlandian_helm_with_visor']"/>
	<xsl:template match="Item[@id='crowned_royal_vlandian_helm_with_visor']"/>
	<xsl:template match="Item[@id='crowned_vlandian_helm_with_visor']"/>
	<xsl:template match="Item[@id='great_prankh_helm']"/>
	<xsl:template match="Item[@id='great_prankh_helm_crest']"/>
	<xsl:template match="Item[@id='great_prankh_helm_winged']"/>
	<xsl:template match="Item[@id='great_prankh_helm_horns']"/>
	<xsl:template match="Item[@id='great_prankh_helm_royal']"/>
	<xsl:template match="Item[@id='Western_chain_shoulders']"/>
	<xsl:template match="Item[@id='mail_with_tabbard1']"/>
	<xsl:template match="Item[@id='mail_with_tabbard2']"/>
	<xsl:template match="Item[@id='mail_with_tabbard3']"/>
	<xsl:template match="Item[@id='mail_with_tabbard4']"/>
	<xsl:template match="Item[@id='mail_with_tabbard5']"/>
	<xsl:template match="Item[@id='Pothelm']"/>
	<xsl:template match="Item[@id='Pothelm2']"/>
	<xsl:template match="Item[@id='Sugarloaf_helm']"/>
	<xsl:template match="Item[@id='Sugarloaf_helm2']"/>
	<xsl:template match="Item[@id='Sugarloaf_helm3']"/>
	<xsl:template match="Item[@id='Sugarloaf_helm4']"/>
	<xsl:template match="Item[@id='plate_boots']"/>
	<xsl:template match="Item[@id='plate_boots2']"/>
	<xsl:template match="Item[@id='sa_bacinet_with_facemask']"/>
	<xsl:template match="Item[@id='sa_1ChurburghHelm']"/>
	<xsl:template match="Item[@id='sa_1ChurburghBoots']"/>
	<xsl:template match="Item[@id='sa_1ChurburghTorso']"/>
	<xsl:template match="Item[@id='sa_1ChurburghGauntlet']"/>
	<xsl:template match="Item[@id='sa_2ChurburghHelm']"/>
	<xsl:template match="Item[@id='sa_2ChurburghBoots']"/>
	<xsl:template match="Item[@id='sa_2ChurburghTorso']"/>
	<xsl:template match="Item[@id='sa_2ChurburghGauntlet']"/>
	<xsl:template match="Item[@id='sa_ChurburghHelm']"/>
	<xsl:template match="Item[@id='sa_ChurburghBoots']"/>
	<xsl:template match="Item[@id='sa_ChurburghTorso']"/>
	<xsl:template match="Item[@id='sa_ChurburghGauntlet']"/>
	<xsl:template match="Item[@id='armet']"/>
	<xsl:template match="Item[@id='armet1']"/>
	<xsl:template match="Item[@id='coat_of_plates6_c']"/>
	<xsl:template match="Item[@id='coat_of_plates7_c']"/>
	<xsl:template match="Item[@id='coat_of_plates8_c']"/>
	<xsl:template match="Item[@id='coat_of_plates9_c']"/>
	<xsl:template match="Item[@id='coat_of_plates10_c']"/>
	<xsl:template match="Item[@id='coat_of_plates11_c']"/>
	<xsl:template match="Item[@id='coat_of_plates12_c']"/>
	<xsl:template match="Item[@id='sa_churburghHelm_black_trimmed_feather']"/>
	<xsl:template match="Item[@id='sa_churburghHelm_feather']"/>
	<xsl:template match="Item[@id='sa_churburghHelm_trimmed_feather']"/>
	<xsl:template match="Item[@id='Sa_brigandine_plate1']"/>
	<xsl:template match="Item[@id='Sa_brigandine_plate2']"/>
	<xsl:template match="Item[@id='Sa_brigandine_plate3']"/>
	<xsl:template match="Item[@id='Sa_brigandine1']"/>
	<xsl:template match="Item[@id='Sa_brigandine2']"/>
	<xsl:template match="Item[@id='Sa_brigandine5']"/>
	<xsl:template match="Item[@id='Sa_brigandine3']"/>
	<xsl:template match="Item[@id='Sa_brigandine4']"/>
	<xsl:template match="Item[@id='Sa_brigandine6']"/>
	<xsl:template match="Item[@id='Sa_tabbartplate']"/>
	<xsl:template match="Item[@id='sa_barbute1']"/>
	<xsl:template match="Item[@id='sa_barbute2']"/>
	<xsl:template match="Item[@id='sa_barbute3']"/>
	<xsl:template match="Item[@id='sa_barbute4']"/>
	<xsl:template match="Item[@id='sacoat1']"/>
	<xsl:template match="Item[@id='sacoat2']"/>
	<xsl:template match="Item[@id='sacoat3']"/>
	<xsl:template match="Item[@id='sa_visoredkettlehelmet']"/>
	<xsl:template match="Item[@id='sa_visoredkettlehelmet1']"/>
	<xsl:template match="Item[@id='sa_butterlord1']"/>
	<xsl:template match="Item[@id='sa_butterlord2']"/>
	<xsl:template match="Item[@id='sa_butterlord3']"/>
	<xsl:template match="Item[@id='sa_butterlord4']"/>
	<xsl:template match="Item[@id='sa_butterlord5']"/>
	<xsl:template match="Item[@id='sa_butterlord6']"/>
	<xsl:template match="Item[@id='sa_butterlord7']"/>
</xsl:stylesheet>