<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<!-- Identity template to copy everything by default -->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_11']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_vlandia_12']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_merch1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_merch2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_merch3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_merch4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_merch5']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_1b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_gangleader_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_gangleader_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_gangleader_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_artisan_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_artisan_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_rural_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_vlandia_rural_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_vlandia_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='npc_gentry_equipment_vlandia']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_battania_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_merchant_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_0b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_0c']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_0d']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_0e']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_1b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_battania_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_rural_notable_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_rural_notable_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_artisan_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_artisan_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_artisan_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_battania_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_battania']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_battania']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_khuzait_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_merchant_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_0b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_1b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_1c']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_2b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_khuzait_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_gangleader_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_gangleader_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_gangleader_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_rural_notable_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_rural_notable_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_artisan_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_artisan_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_artisan_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_khuzait_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_poor_wanderer_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_khuzait']"/>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_empire_11']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_0b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_1b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_2b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_3b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_4b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_11']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_gl1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_gl4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_12']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_13']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_21']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_empire_22']"/>
	<xsl:template match="NPCCharacter[@id='spc_empire_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_empire_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_empire_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_empire']"/>
	<xsl:template match="NPCCharacter[@id='npc_gentry_equipment_empire']"/>
	
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_sturgia_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_0b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_2b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_3b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_3c']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_sturgia_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_sturgia_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_sturgia_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_sturgia_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_sturgia']"/>
	
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_wanderer_aserai_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_0']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_0b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_1b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_2b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_3']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_3b']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_4']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_5']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_6']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_7']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_8']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_9']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_10']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_11']"/>
	<xsl:template match="NPCCharacter[@id='spc_notable_aserai_12']"/>
	<xsl:template match="NPCCharacter[@id='spc_aserai_headman_1']"/>
	<xsl:template match="NPCCharacter[@id='spc_aserai_headman_2']"/>
	<xsl:template match="NPCCharacter[@id='spc_aserai_headman_3']"/>
	<xsl:template match="NPCCharacter[@id='npc_wanderer_equipment_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_artisan_equipment_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_gang_leader_equipment_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_preacher_equipment_aserai']"/>
	<xsl:template match="NPCCharacter[@id='npc_merchant_equipment_aserai']"/>

	
	<xsl:template match="NPCCharacter[@id='spc_ghilman_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_ghilman_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_ghilman_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_ghilman_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_legion_of_the_betrayed_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_legion_of_the_betrayed_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_legion_of_the_betrayed_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_legion_of_the_betrayed_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_karakhuzaits_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_karakhuzaits_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_karakhuzaits_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_karakhuzaits_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_skolderbrotva_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_skolderbrotva_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_skolderbrotva_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_skolderbrotva_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_chosen_of_the_sky_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_chosen_of_the_sky_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_chosen_of_the_sky_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_chosen_of_the_sky_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_jawwal_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_jawwal_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_jawwal_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_jawwal_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_company_of_the_boar_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_company_of_the_boar_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_company_of_the_boar_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_company_of_the_boar_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_beni_zilal_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_beni_zilal_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_beni_zilal_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_beni_zilal_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_hidden_hand_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_hidden_hand_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_hidden_hand_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_hidden_hand_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_lakepike_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_lakepike_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_lakepike_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_lakepike_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_embers_of_flame_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_embers_of_flame_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_embers_of_flame_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_embers_of_flame_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_brotherhood_of_woods_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_brotherhood_of_woods_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_brotherhood_of_woods_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_brotherhood_of_woods_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_forest_people_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_forest_people_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_forest_people_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_forest_people_leader_3']"/>

    <xsl:template match="NPCCharacter[@id='spc_eleftheroi_leader_0']"/>
    <xsl:template match="NPCCharacter[@id='spc_eleftheroi_leader_1']"/>
    <xsl:template match="NPCCharacter[@id='spc_eleftheroi_leader_2']"/>
    <xsl:template match="NPCCharacter[@id='spc_eleftheroi_leader_3']"/>

</xsl:stylesheet>