<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<!-- Identity template to copy everything by default -->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="EquipmentRoster[@id='spc_wanderer_vlandia_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_merch1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_merch4']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_merch5']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_1b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_vlandia_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_vlandia_gangleader_3']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gentry_equipment_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='ather_char_creation_retainer_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_merchant_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_merchant_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_artisan_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_artisan_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_hunter_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_hunter_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_mercenary_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_mercenary_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_vlandia_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_vlandia_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_vlandia_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_vlandia']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_vlandia_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_vlandia_noble_female']"/>
	<!-- -->
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_0b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_0c']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_0d']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_0e']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_1b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_4']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_battania_5']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_battania']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_retainer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_healer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_healer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_artisan_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_artisan_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_hunter_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_hunter_battania']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_bard_battania']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_bard_battania']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_battania_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_battania_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_kern_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_kern_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_battania_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_battania']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_battania_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_battania_noble_female']"/>
	<!-- -->
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_0b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_1b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_1c']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_2b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_khuzait_4']"/>
	<xsl:template match="EquipmentRoster[@id='spc_khuzait_gangleader_3']"/>
	<xsl:template match="EquipmentRoster[@id='npc_poor_wanderer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_retainer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_merchant_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_merchant_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_mercenary_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_mercenary_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_healer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_healer_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_herder_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_herder_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_herder_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_herder_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_khuzait_herder_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_khuzait_herder_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_hunter2_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_khuzait_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_khuzait']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_khuzait_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_khuzait_noble_female']"/>
	<!-- -->
	<xsl:template match="EquipmentRoster[@id='spc_notable_empire_5']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_empire_6']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_empire_7']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_empire_8']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_empire_9']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gentry_equipment_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_retainer_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_merchant_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_merchant_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_artisan_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_artisan_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_hunter_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_hunter_empire']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_vagabond_empire']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_vagabond_empire']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_vagabond_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_vagabond_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_empire_vagabond_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_empire_vagabond_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_empire_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_empire']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_empire_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_empire_noble_female']"/>
	<!-- -->
	
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_0b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_2b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_3b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_3c']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_4']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_5']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_6']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_7']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_sturgia_8']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_retainer_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_merchant_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_merchant_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_artisan_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_artisan_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_hunter_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_hunter_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_vagabond_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_vagabond_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_merchant_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_merchant_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_vagabond_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_vagabond_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_sturgia_vagabond_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_sturgia_vagabond_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_sturgia_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_default']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_sturgia']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_sturgia_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_sturgia_noble_male']"/>
	
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_0b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_1b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_2b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_3b']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_4']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_5']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_6']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_7']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_8']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_9']"/>
	<xsl:template match="EquipmentRoster[@id='spc_notable_aserai_10']"/>
	<xsl:template match="EquipmentRoster[@id='npc_wanderer_equipment_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_artisan_equipment_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_gang_leader_equipment_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_preacher_equipment_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='npc_merchant_equipment_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_retainer_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_retainer_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_mercenary_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_mercenary_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_physician_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_physician_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_farmer_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_farmer_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_herder_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_herder_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='mother_char_creation_artisan_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='father_char_creation_artisan_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_healer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_healer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_physician_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_physician_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_physician_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_physician_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_farmer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_farmer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_herder_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_herder_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_herder_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_herder_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_artisan_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_childhood_age_aserai_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_education_age_aserai_artisan_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_guard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_guard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_hunter_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_hunter_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_retainer_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_retainer_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_infantry_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_infantry_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_skirmisher_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_skirmisher_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_bard_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_bard_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_6_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_6_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_mercenary_m']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_aserai_mercenary_f']"/>
	<xsl:template match="EquipmentRoster[@id='player_char_creation_show_aserai']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_townsman_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_townsman_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_villager_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_villager_female']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='child_template_aserai_noble_female']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_noble_male']"/>
	<xsl:template match="EquipmentRoster[@id='teenager_template_aserai_noble_female']"/>
	
	
</xsl:stylesheet>