<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
	<!-- Identity template to copy everything by default -->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- -->
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_one_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_one_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v4']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v4']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='barber_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='musician_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='armorer_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='beggar_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_vlandia']"/>
	<!--  -->
	<xsl:template match="NPCCharacter[@id='prison_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_battania']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_battania']"/>
	<xsl:template match="NPCCharacter[@id='barber_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_battania']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_battania']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_battania']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_battania']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_battania']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_battania']"/>
	<xsl:template match="NPCCharacter[@id='musician_battania']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_battania']"/>
	<xsl:template match="NPCCharacter[@id='armorer_battania']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_battania']"/>
	<xsl:template match="NPCCharacter[@id='merchant_battania']"/>
	<xsl:template match="NPCCharacter[@id='beggar_battania']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_battania']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_battania']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_battania']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_battania']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_battania']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_battania']"/>
	<!--  -->
	<xsl:template match="NPCCharacter[@id='prison_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='barber_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='musician_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='armorer_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='merchant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='beggar_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_khuzait']"/>
	<!--  -->
	<xsl:template match="NPCCharacter[@id='prison_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_empire']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_empire']"/>
	<xsl:template match="NPCCharacter[@id='barber_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_empire']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_empire']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_empire']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_empire']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_empire']"/>
	<xsl:template match="NPCCharacter[@id='musician_empire']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_empire']"/>
	<xsl:template match="NPCCharacter[@id='armorer_empire']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_empire']"/>
	<xsl:template match="NPCCharacter[@id='merchant_empire']"/>
	<xsl:template match="NPCCharacter[@id='beggar_empire']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_empire']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_empire']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_empire']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_empire']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_empire']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_empire']"/>
	
	<xsl:template match="NPCCharacter[@id='prison_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='barber_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='musician_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='armorer_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='beggar_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_sturgia']"/>
	
	<xsl:template match="NPCCharacter[@id='prison_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_aserai']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_aserai']"/>
	<xsl:template match="NPCCharacter[@id='barber_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_aserai']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_aserai']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_aserai']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_aserai']"/>
	<xsl:template match="NPCCharacter[@id='musician_aserai']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_aserai']"/>
	<xsl:template match="NPCCharacter[@id='armorer_aserai']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='merchant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='beggar_aserai']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_aserai']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_aserai']"/>
	<xsl:template match="NPCCharacter[@id='tournament_master_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_aserai']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_aserai']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_aserai']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='player_char_creation_aserai']"/>
	
	
	
</xsl:stylesheet>